name: Upload V8 coverage
description: Upload V8 coverage artifacts.
inputs:
  name:
    description: Artifact name.
    required: true

runs:
  using: composite
  steps:
    - name: Normalize artifact name
      id: normalize
      shell: bash
      run: |
        name="${{ inputs.name }}"
        echo "name=${name//\//-}" >> "$GITHUB_OUTPUT"

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.normalize.outputs.name }}
        path: ${{ env.NODE_V8_COVERAGE }}
