// Code generated by go generate; DO NOT EDIT.

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package stagehand

import "encoding/json"

type ActOptions struct {
	// Cache corresponds to the JSON schema field "cache".
	Cache *Caching `json:"cache,omitempty"`

	// Serializable element locator for the action target
	Locator *Locator `json:"locator,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *ModelConfig `json:"model,omitempty"`

	// Timeout in ms for the action
	Timeout *float64 `json:"timeout,omitempty"`

	// Variables to substitute in the action instruction. Accepts flat primitives or {
	// value, description? } objects.
	Variables Variables `json:"variables,omitempty"`
}

type ActResult struct {
	// Action ID for tracking
	ActionID *string `json:"action_id,omitempty"`

	// Server-side cache status for this result
	CacheStatus *CacheStatus `json:"cache_status,omitempty"`

	// Result corresponds to the JSON schema field "result".
	Result ActResultData `json:"result"`
}

type ActResultData struct {
	// Description of the action that was performed
	ActionDescription string `json:"action_description"`

	// List of actions that were executed
	Actions []Action `json:"actions"`

	// Human-readable result message
	Message string `json:"message"`

	// Whether the action completed successfully
	Success bool `json:"success"`
}

// Action object returned by observe and used by act
type Action struct {
	// Arguments to pass to the method
	Arguments []string `json:"arguments,omitempty"`

	// Human-readable description of the action
	Description string `json:"description"`

	// The method to execute (click, fill, etc.)
	Method *string `json:"method,omitempty"`

	// CSS selector or XPath for the element
	Selector string `json:"selector"`
}

type AnthropicModelName string

type BrowserGetVersionResult struct {
	// JSVersion corresponds to the JSON schema field "js_version".
	JSVersion *string `json:"js_version,omitempty"`

	// Product corresponds to the JSON schema field "product".
	Product *string `json:"product,omitempty"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion *string `json:"protocol_version,omitempty"`

	// Revision corresponds to the JSON schema field "revision".
	Revision *string `json:"revision,omitempty"`

	// UserAgent corresponds to the JSON schema field "user_agent".
	UserAgent *string `json:"user_agent,omitempty"`
}

type BrowserbaseBrowserSettings struct {
	// AdvancedStealth corresponds to the JSON schema field "advanced_stealth".
	AdvancedStealth *bool `json:"advanced_stealth,omitempty"`

	// BlockAds corresponds to the JSON schema field "block_ads".
	BlockAds *bool `json:"block_ads,omitempty"`

	// CaptchaImageSelector corresponds to the JSON schema field
	// "captcha_image_selector".
	CaptchaImageSelector *string `json:"captcha_image_selector,omitempty"`

	// CaptchaInputSelector corresponds to the JSON schema field
	// "captcha_input_selector".
	CaptchaInputSelector *string `json:"captcha_input_selector,omitempty"`

	// Context corresponds to the JSON schema field "context".
	Context *BrowserbaseContext `json:"context,omitempty"`

	// ExtensionID corresponds to the JSON schema field "extension_id".
	ExtensionID *string `json:"extension_id,omitempty"`

	// Fingerprint corresponds to the JSON schema field "fingerprint".
	Fingerprint *BrowserbaseFingerprint `json:"fingerprint,omitempty"`

	// LogSession corresponds to the JSON schema field "log_session".
	LogSession *bool `json:"log_session,omitempty"`

	// OS corresponds to the JSON schema field "os".
	OS *BrowserbaseBrowserSettingsOS `json:"os,omitempty"`

	// RecordSession corresponds to the JSON schema field "record_session".
	RecordSession *bool `json:"record_session,omitempty"`

	// SolveCaptchas corresponds to the JSON schema field "solve_captchas".
	SolveCaptchas *bool `json:"solve_captchas,omitempty"`

	// Verified corresponds to the JSON schema field "verified".
	Verified *bool `json:"verified,omitempty"`

	// Viewport corresponds to the JSON schema field "viewport".
	Viewport *BrowserbaseViewport `json:"viewport,omitempty"`
}

type BrowserbaseBrowserSettingsOS string

const BrowserbaseBrowserSettingsOSLinux BrowserbaseBrowserSettingsOS = "linux"
const BrowserbaseBrowserSettingsOSMac BrowserbaseBrowserSettingsOS = "mac"
const BrowserbaseBrowserSettingsOSMobile BrowserbaseBrowserSettingsOS = "mobile"
const BrowserbaseBrowserSettingsOSTablet BrowserbaseBrowserSettingsOS = "tablet"
const BrowserbaseBrowserSettingsOSWindows BrowserbaseBrowserSettingsOS = "windows"

type BrowserbaseBrowserSource struct {
	// BrowserSettings corresponds to the JSON schema field "browser_settings".
	BrowserSettings *BrowserbaseBrowserSettings `json:"browser_settings,omitempty"`

	// ExtensionID corresponds to the JSON schema field "extension_id".
	ExtensionID *string `json:"extension_id,omitempty"`

	// KeepAlive corresponds to the JSON schema field "keep_alive".
	KeepAlive *bool `json:"keep_alive,omitempty"`

	// Proxies corresponds to the JSON schema field "proxies".
	Proxies *BrowserbaseProxies `json:"proxies,omitempty"`

	// Region corresponds to the JSON schema field "region".
	Region *BrowserbaseRegion `json:"region,omitempty"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout *float64 `json:"timeout,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// UserMetadata corresponds to the JSON schema field "user_metadata".
	UserMetadata map[string]json.RawMessage `json:"user_metadata,omitempty"`
}

type BrowserbaseContext struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Persist corresponds to the JSON schema field "persist".
	Persist *bool `json:"persist,omitempty"`
}

type BrowserbaseFingerprint struct {
	// Browsers corresponds to the JSON schema field "browsers".
	Browsers []BrowserbaseFingerprintBrowsersElem `json:"browsers,omitempty"`

	// Devices corresponds to the JSON schema field "devices".
	Devices []BrowserbaseFingerprintDevicesElem `json:"devices,omitempty"`

	// HTTPVersion corresponds to the JSON schema field "http_version".
	HTTPVersion *BrowserbaseFingerprintHTTPVersion `json:"http_version,omitempty"`

	// Locales corresponds to the JSON schema field "locales".
	Locales []string `json:"locales,omitempty"`

	// OperatingSystems corresponds to the JSON schema field "operating_systems".
	OperatingSystems []BrowserbaseFingerprintOperatingSystemsElem `json:"operating_systems,omitempty"`

	// Screen corresponds to the JSON schema field "screen".
	Screen *BrowserbaseFingerprintScreen `json:"screen,omitempty"`
}

type BrowserbaseFingerprintBrowsersElem string

const BrowserbaseFingerprintBrowsersElemChrome BrowserbaseFingerprintBrowsersElem = "chrome"
const BrowserbaseFingerprintBrowsersElemEdge BrowserbaseFingerprintBrowsersElem = "edge"
const BrowserbaseFingerprintBrowsersElemFirefox BrowserbaseFingerprintBrowsersElem = "firefox"
const BrowserbaseFingerprintBrowsersElemSafari BrowserbaseFingerprintBrowsersElem = "safari"

type BrowserbaseFingerprintDevicesElem string

const BrowserbaseFingerprintDevicesElemDesktop BrowserbaseFingerprintDevicesElem = "desktop"
const BrowserbaseFingerprintDevicesElemMobile BrowserbaseFingerprintDevicesElem = "mobile"

type BrowserbaseFingerprintHTTPVersion string

const BrowserbaseFingerprintHTTPVersionA1 BrowserbaseFingerprintHTTPVersion = "1"
const BrowserbaseFingerprintHTTPVersionA2 BrowserbaseFingerprintHTTPVersion = "2"

type BrowserbaseFingerprintOperatingSystemsElem string

const BrowserbaseFingerprintOperatingSystemsElemAndroid BrowserbaseFingerprintOperatingSystemsElem = "android"
const BrowserbaseFingerprintOperatingSystemsElemIOS BrowserbaseFingerprintOperatingSystemsElem = "ios"
const BrowserbaseFingerprintOperatingSystemsElemLinux BrowserbaseFingerprintOperatingSystemsElem = "linux"
const BrowserbaseFingerprintOperatingSystemsElemMacos BrowserbaseFingerprintOperatingSystemsElem = "macos"
const BrowserbaseFingerprintOperatingSystemsElemWindows BrowserbaseFingerprintOperatingSystemsElem = "windows"

type BrowserbaseFingerprintScreen struct {
	// MaxHeight corresponds to the JSON schema field "max_height".
	MaxHeight *float64 `json:"max_height,omitempty"`

	// MaxWidth corresponds to the JSON schema field "max_width".
	MaxWidth *float64 `json:"max_width,omitempty"`

	// MinHeight corresponds to the JSON schema field "min_height".
	MinHeight *float64 `json:"min_height,omitempty"`

	// MinWidth corresponds to the JSON schema field "min_width".
	MinWidth *float64 `json:"min_width,omitempty"`
}

type BrowserbaseProxyConfig struct {
	// DomainPattern corresponds to the JSON schema field "domain_pattern".
	DomainPattern *string `json:"domain_pattern,omitempty"`

	// Geolocation corresponds to the JSON schema field "geolocation".
	Geolocation *BrowserbaseProxyGeolocation `json:"geolocation,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type BrowserbaseProxyGeolocation struct {
	// City corresponds to the JSON schema field "city".
	City *string `json:"city,omitempty"`

	// Country corresponds to the JSON schema field "country".
	Country string `json:"country"`

	// State corresponds to the JSON schema field "state".
	State *string `json:"state,omitempty"`
}

type BrowserbaseRegion string

const BrowserbaseRegionAPSoutheast1 BrowserbaseRegion = "ap-southeast-1"
const BrowserbaseRegionEUCentral1 BrowserbaseRegion = "eu-central-1"
const BrowserbaseRegionUSEast1 BrowserbaseRegion = "us-east-1"
const BrowserbaseRegionUSWest2 BrowserbaseRegion = "us-west-2"

type BrowserbaseViewport struct {
	// Height corresponds to the JSON schema field "height".
	Height *float64 `json:"height,omitempty"`

	// Width corresponds to the JSON schema field "width".
	Width *float64 `json:"width,omitempty"`
}

type CacheStatus string

const CacheStatusHIT CacheStatus = "HIT"
const CacheStatusMISS CacheStatus = "MISS"

type CerebrasModelName string

type ClearCookieOptions struct {
	// Domain corresponds to the JSON schema field "domain".
	Domain *CookieFilter `json:"domain,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *CookieFilter `json:"name,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path *CookieFilter `json:"path,omitempty"`
}

type ClientModelReference struct {
	// Source corresponds to the JSON schema field "source".
	Source string `json:"source"`
}

type ContextAddCookiesParams struct {
	// Cookies corresponds to the JSON schema field "cookies".
	Cookies []CookieParam `json:"cookies"`
}

type ContextAddInitScriptParams struct {
	// Source corresponds to the JSON schema field "source".
	Source string `json:"source"`
}

type ContextClearCookiesParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *ClearCookieOptions `json:"options,omitempty"`
}

type ContextClipboardPasteParams struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID *string `json:"page_id,omitempty"`

	// Shortcut corresponds to the JSON schema field "shortcut".
	Shortcut *ContextClipboardPasteParamsShortcut `json:"shortcut,omitempty"`
}

type ContextClipboardPasteParamsShortcut string

const ContextClipboardPasteParamsShortcutControlOrMetaV ContextClipboardPasteParamsShortcut = "ControlOrMeta+V"
const ContextClipboardPasteParamsShortcutControlV ContextClipboardPasteParamsShortcut = "Control+V"
const ContextClipboardPasteParamsShortcutMetaV ContextClipboardPasteParamsShortcut = "Meta+V"

type ContextClipboardReadTextResult struct {
	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`
}

type ContextClipboardTarget struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID *string `json:"page_id,omitempty"`
}

type ContextClipboardWriteTextParams struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID *string `json:"page_id,omitempty"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`
}

type ContextCloseResult struct {
	// Closed corresponds to the JSON schema field "closed".
	Closed bool `json:"closed"`
}

type ContextCookiesParams struct {
	// Urls corresponds to the JSON schema field "urls".
	Urls *StringList `json:"urls,omitempty"`
}

type ContextCookiesResult struct {
	// Cookies corresponds to the JSON schema field "cookies".
	Cookies []Cookie `json:"cookies"`
}

type ContextGetDomainPolicyResult struct {
	// Policy corresponds to the JSON schema field "policy".
	Policy *DomainPolicy `json:"policy"`
}

type ContextNewPageParams struct {
	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty"`
}

type ContextPagesResult []PageRef

type ContextSetActivePageParams struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type ContextSetDomainPolicyParams struct {
	// Policy corresponds to the JSON schema field "policy".
	Policy *DomainPolicy `json:"policy"`
}

type ContextSetExtraHTTPHeadersParams struct {
	// Headers corresponds to the JSON schema field "headers".
	Headers ContextSetExtraHTTPHeadersParamsHeaders `json:"headers"`
}

type ContextSetExtraHTTPHeadersParamsHeaders map[string]string

type ContextVoidResult struct {
	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`
}

type Cookie struct {
	// Domain corresponds to the JSON schema field "domain".
	Domain string `json:"domain"`

	// Expires corresponds to the JSON schema field "expires".
	Expires float64 `json:"expires"`

	// HTTPOnly corresponds to the JSON schema field "http_only".
	HTTPOnly bool `json:"http_only"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// SameSite corresponds to the JSON schema field "same_site".
	SameSite CookieSameSite `json:"same_site"`

	// Secure corresponds to the JSON schema field "secure".
	Secure bool `json:"secure"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type CookieParam struct {
	// Domain corresponds to the JSON schema field "domain".
	Domain *string `json:"domain,omitempty"`

	// Expires corresponds to the JSON schema field "expires".
	Expires *float64 `json:"expires,omitempty"`

	// HTTPOnly corresponds to the JSON schema field "http_only".
	HTTPOnly *bool `json:"http_only,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`

	// SameSite corresponds to the JSON schema field "same_site".
	SameSite *CookieParamSameSite `json:"same_site,omitempty"`

	// Secure corresponds to the JSON schema field "secure".
	Secure *bool `json:"secure,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type CookieParamSameSite string

const CookieParamSameSiteLax CookieParamSameSite = "Lax"
const CookieParamSameSiteNone CookieParamSameSite = "None"
const CookieParamSameSiteStrict CookieParamSameSite = "Strict"

type CookieRegex struct {
	// Flags corresponds to the JSON schema field "flags".
	Flags *string `json:"flags,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source"`
}

type CookieSameSite string

const CookieSameSiteLax CookieSameSite = "Lax"
const CookieSameSiteNone CookieSameSite = "None"
const CookieSameSiteStrict CookieSameSite = "Strict"

type CustomModelConfig struct {
	// API key for the model provider
	APIKey *string `json:"api_key,omitempty"`

	// Base URL for the custom OpenAI-compatible endpoint
	BaseURL string `json:"base_url"`

	// Custom headers sent with every request to the model provider
	Headers CustomModelConfigHeaders `json:"headers,omitempty"`

	// Model name accepted by the custom OpenAI-compatible endpoint
	ModelName string `json:"model_name"`
}

// Custom headers sent with every request to the model provider
type CustomModelConfigHeaders map[string]string

type DescribedVariableValue struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value VariablePrimitive `json:"value"`
}

type DomainPolicy struct {
	// AllowedDomains corresponds to the JSON schema field "allowed_domains".
	AllowedDomains []string `json:"allowed_domains,omitempty"`

	// BlockedDomains corresponds to the JSON schema field "blocked_domains".
	BlockedDomains []string `json:"blocked_domains,omitempty"`
}

type ExternalProxyConfig struct {
	// DomainPattern corresponds to the JSON schema field "domain_pattern".
	DomainPattern *string `json:"domain_pattern,omitempty"`

	// Password corresponds to the JSON schema field "password".
	Password *string `json:"password,omitempty"`

	// Server corresponds to the JSON schema field "server".
	Server string `json:"server"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// Username corresponds to the JSON schema field "username".
	Username *string `json:"username,omitempty"`
}

type ExtractOptions struct {
	// Cache corresponds to the JSON schema field "cache".
	Cache *Caching `json:"cache,omitempty"`

	// Selectors for elements and subtrees that should be excluded from extraction
	IgnoreSelectors []string `json:"ignore_selectors,omitempty"`

	// Serializable element locator for the extraction target
	Locator *Locator `json:"locator,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *ModelConfig `json:"model,omitempty"`

	// When true, include a screenshot of the current viewport in the extraction LLM
	// call. Defaults to false.
	Screenshot *bool `json:"screenshot,omitempty"`

	// CSS selector to scope extraction to a specific element
	Selector *string `json:"selector,omitempty"`

	// Timeout in ms for the extraction
	Timeout *float64 `json:"timeout,omitempty"`
}

type ExtractResult struct {
	// Action ID for tracking
	ActionID *string `json:"action_id,omitempty"`

	// Server-side cache status for this result
	CacheStatus *CacheStatus `json:"cache_status,omitempty"`

	// Result corresponds to the JSON schema field "result".
	Result json.RawMessage `json:"result"`
}

type GoogleModelName string

type GroqModelName string

type ImplementationInfo struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

type KnownModelConfig struct {
	// API key for the model provider
	APIKey *string `json:"api_key,omitempty"`

	// Custom headers sent with every request to the model provider
	Headers KnownModelConfigHeaders `json:"headers,omitempty"`

	// ModelName corresponds to the JSON schema field "model_name".
	ModelName ModelName `json:"model_name"`
}

// Custom headers sent with every request to the model provider
type KnownModelConfigHeaders map[string]string

type LLMAnnotations struct {
	// Audience corresponds to the JSON schema field "audience".
	Audience []LLMRole `json:"audience,omitempty"`

	// LastModified corresponds to the JSON schema field "last_modified".
	LastModified *string `json:"last_modified,omitempty"`

	// Priority corresponds to the JSON schema field "priority".
	Priority *float64 `json:"priority,omitempty"`
}

type LLMClientTool struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations *LLMToolAnnotations `json:"annotations,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// Execution corresponds to the JSON schema field "execution".
	Execution *LLMToolExecution `json:"execution,omitempty"`

	// Icons corresponds to the JSON schema field "icons".
	Icons []LLMToolIcon `json:"icons,omitempty"`

	// InputSchema corresponds to the JSON schema field "input_schema".
	InputSchema LLMToolJSON `json:"input_schema"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// OutputSchema corresponds to the JSON schema field "output_schema".
	OutputSchema *LLMToolJSON `json:"output_schema,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title *string `json:"title,omitempty"`
}

type LLMImageContent struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations *LLMAnnotations `json:"annotations,omitempty"`

	// Data corresponds to the JSON schema field "data".
	Data string `json:"data"`

	// MIMEType corresponds to the JSON schema field "mime_type".
	MIMEType string `json:"mime_type"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LLMJSONSchemaResponseFormat struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Schema corresponds to the JSON schema field "schema".
	Schema json.RawMessage `json:"schema"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LLMMessage struct {
	// Content corresponds to the JSON schema field "content".
	Content LLMMessageContent `json:"content"`

	// Role corresponds to the JSON schema field "role".
	Role LLMRole `json:"role"`
}

type LLMMessageGenerateParams struct {
	// Messages corresponds to the JSON schema field "messages".
	Messages []LLMMessage `json:"messages"`

	// ResponseFormat corresponds to the JSON schema field "response_format".
	ResponseFormat *LLMTextResponseFormat `json:"response_format,omitempty"`

	// StopSequences corresponds to the JSON schema field "stop_sequences".
	StopSequences []string `json:"stop_sequences,omitempty"`

	// SystemPrompt corresponds to the JSON schema field "system_prompt".
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature *float64 `json:"temperature,omitempty"`

	// ToolChoice corresponds to the JSON schema field "tool_choice".
	ToolChoice *LLMToolChoice `json:"tool_choice,omitempty"`

	// Tools corresponds to the JSON schema field "tools".
	Tools []LLMClientTool `json:"tools,omitempty"`
}

type LLMRole string

const LLMRoleAssistant LLMRole = "assistant"
const LLMRoleUser LLMRole = "user"

type LLMStructuredGenerateParams struct {
	// Messages corresponds to the JSON schema field "messages".
	Messages []LLMMessage `json:"messages"`

	// ResponseFormat corresponds to the JSON schema field "response_format".
	ResponseFormat LLMJSONSchemaResponseFormat `json:"response_format"`

	// StopSequences corresponds to the JSON schema field "stop_sequences".
	StopSequences []string `json:"stop_sequences,omitempty"`

	// SystemPrompt corresponds to the JSON schema field "system_prompt".
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature *float64 `json:"temperature,omitempty"`
}

type LLMTextContent struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations *LLMAnnotations `json:"annotations,omitempty"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LLMTextResponseFormat struct {
	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LLMToolAnnotations struct {
	// DestructiveHint corresponds to the JSON schema field "destructive_hint".
	DestructiveHint *bool `json:"destructive_hint,omitempty"`

	// IdempotentHint corresponds to the JSON schema field "idempotent_hint".
	IdempotentHint *bool `json:"idempotent_hint,omitempty"`

	// OpenWorldHint corresponds to the JSON schema field "open_world_hint".
	OpenWorldHint *bool `json:"open_world_hint,omitempty"`

	// ReadOnlyHint corresponds to the JSON schema field "read_only_hint".
	ReadOnlyHint *bool `json:"read_only_hint,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title *string `json:"title,omitempty"`
}

type LLMToolChoice struct {
	// Mode corresponds to the JSON schema field "mode".
	Mode *LLMToolChoiceMode `json:"mode,omitempty"`
}

type LLMToolChoiceMode string

const LLMToolChoiceModeAuto LLMToolChoiceMode = "auto"
const LLMToolChoiceModeNone LLMToolChoiceMode = "none"
const LLMToolChoiceModeRequired LLMToolChoiceMode = "required"

type LLMToolExecution struct {
	// TaskSupport corresponds to the JSON schema field "task_support".
	TaskSupport *LLMToolExecutionTaskSupport `json:"task_support,omitempty"`
}

type LLMToolExecutionTaskSupport string

const LLMToolExecutionTaskSupportForbidden LLMToolExecutionTaskSupport = "forbidden"
const LLMToolExecutionTaskSupportOptional LLMToolExecutionTaskSupport = "optional"
const LLMToolExecutionTaskSupportRequired LLMToolExecutionTaskSupport = "required"

type LLMToolIcon struct {
	// MIMEType corresponds to the JSON schema field "mime_type".
	MIMEType *string `json:"mime_type,omitempty"`

	// Sizes corresponds to the JSON schema field "sizes".
	Sizes []string `json:"sizes,omitempty"`

	// Src corresponds to the JSON schema field "src".
	Src string `json:"src"`

	// Theme corresponds to the JSON schema field "theme".
	Theme *LLMToolIconTheme `json:"theme,omitempty"`
}

type LLMToolIconTheme string

const LLMToolIconThemeDark LLMToolIconTheme = "dark"
const LLMToolIconThemeLight LLMToolIconTheme = "light"

type LLMToolJSON struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema *string `json:"$schema,omitempty"`

	// Properties corresponds to the JSON schema field "properties".
	Properties LLMToolJSONProperties `json:"properties,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required []string `json:"required,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LLMToolJSONProperties map[string]map[string]json.RawMessage

type LLMToolResultContent struct {
	// Content corresponds to the JSON schema field "content".
	Content []LLMToolResultContentBlock `json:"content"`

	// IsError corresponds to the JSON schema field "is_error".
	IsError *bool `json:"is_error,omitempty"`

	// StructuredContent corresponds to the JSON schema field "structured_content".
	StructuredContent LLMToolResultContentStructuredContent `json:"structured_content,omitempty"`

	// ToolUseID corresponds to the JSON schema field "tool_use_id".
	ToolUseID string `json:"tool_use_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LLMToolResultContentStructuredContent map[string]json.RawMessage

type LLMToolUseContent struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Input corresponds to the JSON schema field "input".
	Input LLMToolUseContentInput `json:"input"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LLMToolUseContentInput map[string]json.RawMessage

type LLMUsage struct {
	// CachedInputTokens corresponds to the JSON schema field "cached_input_tokens".
	CachedInputTokens *int `json:"cached_input_tokens,omitempty"`

	// InputTokens corresponds to the JSON schema field "input_tokens".
	InputTokens int `json:"input_tokens"`

	// OutputTokens corresponds to the JSON schema field "output_tokens".
	OutputTokens int `json:"output_tokens"`

	// ReasoningTokens corresponds to the JSON schema field "reasoning_tokens".
	ReasoningTokens *int `json:"reasoning_tokens,omitempty"`

	// TotalTokens corresponds to the JSON schema field "total_tokens".
	TotalTokens int `json:"total_tokens"`
}

type Locator struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`
}

type LocatorCentroidResult struct {
	// X corresponds to the JSON schema field "x".
	X float64 `json:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y"`
}

type LocatorClickOptions struct {
	// Button corresponds to the JSON schema field "button".
	Button *MouseButton `json:"button,omitempty"`

	// ClickCount corresponds to the JSON schema field "click_count".
	ClickCount *int `json:"click_count,omitempty"`
}

type LocatorClickParams struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *LocatorClickOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`
}

type LocatorClickResult struct {
	// Clicked corresponds to the JSON schema field "clicked".
	Clicked bool `json:"clicked"`
}

type LocatorCountResult struct {
	// Count corresponds to the JSON schema field "count".
	Count int `json:"count"`
}

type LocatorDescriptor struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`
}

type LocatorFillParams struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type LocatorFillResult struct {
	// Filled corresponds to the JSON schema field "filled".
	Filled bool `json:"filled"`
}

type LocatorHighlightOptions struct {
	// BorderColor corresponds to the JSON schema field "border_color".
	BorderColor *RgbaColor `json:"border_color,omitempty"`

	// ContentColor corresponds to the JSON schema field "content_color".
	ContentColor *RgbaColor `json:"content_color,omitempty"`

	// DurationMs corresponds to the JSON schema field "duration_ms".
	DurationMs *int `json:"duration_ms,omitempty"`
}

type LocatorHighlightParams struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *LocatorHighlightOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`
}

type LocatorHighlightResult struct {
	// Highlighted corresponds to the JSON schema field "highlighted".
	Highlighted bool `json:"highlighted"`
}

type LocatorHoverResult struct {
	// Hovered corresponds to the JSON schema field "hovered".
	Hovered bool `json:"hovered"`
}

type LocatorInnerHTMLResult struct {
	// HTML corresponds to the JSON schema field "html".
	HTML string `json:"html"`
}

type LocatorInnerTextResult struct {
	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`
}

type LocatorInputValueResult struct {
	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type LocatorIsCheckedResult struct {
	// Checked corresponds to the JSON schema field "checked".
	Checked bool `json:"checked"`
}

type LocatorIsVisibleResult struct {
	// Visible corresponds to the JSON schema field "visible".
	Visible bool `json:"visible"`
}

type LocatorScrollToParams struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Percent corresponds to the JSON schema field "percent".
	Percent ScrollPercent `json:"percent"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`
}

type LocatorScrollToResult struct {
	// Scrolled corresponds to the JSON schema field "scrolled".
	Scrolled bool `json:"scrolled"`
}

type LocatorSelectOptionParams struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`

	// Values corresponds to the JSON schema field "values".
	Values StringList `json:"values"`
}

type LocatorSelectOptionResult struct {
	// Values corresponds to the JSON schema field "values".
	Values []string `json:"values"`
}

type LocatorSendClickEventOptions struct {
	// Bubbles corresponds to the JSON schema field "bubbles".
	Bubbles *bool `json:"bubbles,omitempty"`

	// Cancelable corresponds to the JSON schema field "cancelable".
	Cancelable *bool `json:"cancelable,omitempty"`

	// Composed corresponds to the JSON schema field "composed".
	Composed *bool `json:"composed,omitempty"`

	// Detail corresponds to the JSON schema field "detail".
	Detail *float64 `json:"detail,omitempty"`
}

type LocatorSendClickEventParams struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *LocatorSendClickEventOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`
}

type LocatorSendClickEventResult struct {
	// Clicked corresponds to the JSON schema field "clicked".
	Clicked bool `json:"clicked"`
}

type LocatorTextContentResult struct {
	// TextContent corresponds to the JSON schema field "text_content".
	TextContent string `json:"text_content"`
}

type LocatorTypeOptions struct {
	// Delay corresponds to the JSON schema field "delay".
	Delay *float64 `json:"delay,omitempty"`
}

type LocatorTypeParams struct {
	// Nth corresponds to the JSON schema field "nth".
	Nth *int `json:"nth,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *LocatorTypeOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`
}

type LocatorTypeResult struct {
	// Typed corresponds to the JSON schema field "typed".
	Typed bool `json:"typed"`
}

type MouseButton string

const MouseButtonLeft MouseButton = "left"
const MouseButtonMiddle MouseButton = "middle"
const MouseButtonRight MouseButton = "right"

type ObserveOptions struct {
	// Cache corresponds to the JSON schema field "cache".
	Cache *Caching `json:"cache,omitempty"`

	// Selectors for elements and subtrees that should be excluded from observation
	IgnoreSelectors []string `json:"ignore_selectors,omitempty"`

	// Serializable element locator for the observation target
	Locator *Locator `json:"locator,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *ModelConfig `json:"model,omitempty"`

	// CSS selector to scope observation to a specific element
	Selector *string `json:"selector,omitempty"`

	// Timeout in ms for the observation
	Timeout *float64 `json:"timeout,omitempty"`

	// Variables whose names are exposed to the model so observe() returns
	// %variableName% placeholders in suggested action arguments instead of literal
	// values. Accepts flat primitives or { value, description? } objects.
	Variables Variables `json:"variables,omitempty"`
}

type ObserveResult struct {
	// Action ID for tracking
	ActionID *string `json:"action_id,omitempty"`

	// Server-side cache status for this result
	CacheStatus *CacheStatus `json:"cache_status,omitempty"`

	// Result corresponds to the JSON schema field "result".
	Result []Action `json:"result"`
}

type OpenAIModelName string

type PageAddInitScriptParams struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source"`
}

type PageClickOptions struct {
	// Button corresponds to the JSON schema field "button".
	Button *MouseButton `json:"button,omitempty"`

	// ClickCount corresponds to the JSON schema field "click_count".
	ClickCount *int `json:"click_count,omitempty"`

	// ReturnXPath corresponds to the JSON schema field "return_xpath".
	ReturnXPath *bool `json:"return_xpath,omitempty"`
}

type PageClickParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageClickOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// X corresponds to the JSON schema field "x".
	X float64 `json:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y"`
}

type PageCloseResult struct {
	// Closed corresponds to the JSON schema field "closed".
	Closed bool `json:"closed"`
}

type PageCoordinateResult struct {
	// XPath corresponds to the JSON schema field "xpath".
	XPath string `json:"xpath"`
}

type PageDragAndDropOptions struct {
	// Button corresponds to the JSON schema field "button".
	Button *MouseButton `json:"button,omitempty"`

	// Delay corresponds to the JSON schema field "delay".
	Delay *float64 `json:"delay,omitempty"`

	// ReturnXPath corresponds to the JSON schema field "return_xpath".
	ReturnXPath *bool `json:"return_xpath,omitempty"`

	// Steps corresponds to the JSON schema field "steps".
	Steps *int `json:"steps,omitempty"`
}

type PageDragAndDropParams struct {
	// FromX corresponds to the JSON schema field "from_x".
	FromX float64 `json:"from_x"`

	// FromY corresponds to the JSON schema field "from_y".
	FromY float64 `json:"from_y"`

	// Options corresponds to the JSON schema field "options".
	Options *PageDragAndDropOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// ToX corresponds to the JSON schema field "to_x".
	ToX float64 `json:"to_x"`

	// ToY corresponds to the JSON schema field "to_y".
	ToY float64 `json:"to_y"`
}

type PageDragAndDropResult struct {
	// FromXPath corresponds to the JSON schema field "from_xpath".
	FromXPath string `json:"from_xpath"`

	// ToXPath corresponds to the JSON schema field "to_xpath".
	ToXPath string `json:"to_xpath"`
}

type PageEvaluateParams struct {
	// Expression corresponds to the JSON schema field "expression".
	Expression string `json:"expression"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageEvaluateResult struct {
	// Value corresponds to the JSON schema field "value".
	Value json.RawMessage `json:"value"`
}

type PageGoBackParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageNavigationOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageGoForwardParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageNavigationOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageGotoParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageNavigationOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url"`
}

type PageHoverOptions struct {
	// ReturnXPath corresponds to the JSON schema field "return_xpath".
	ReturnXPath *bool `json:"return_xpath,omitempty"`
}

type PageHoverParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageHoverOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// X corresponds to the JSON schema field "x".
	X float64 `json:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y"`
}

type PageIDParams struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageKeyPressOptions struct {
	// Delay corresponds to the JSON schema field "delay".
	Delay *float64 `json:"delay,omitempty"`
}

type PageKeyPressParams struct {
	// Key corresponds to the JSON schema field "key".
	Key string `json:"key"`

	// Options corresponds to the JSON schema field "options".
	Options *PageKeyPressOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageNavigationOptions struct {
	// Timeout corresponds to the JSON schema field "timeout".
	Timeout *int `json:"timeout,omitempty"`

	// WaitUntil corresponds to the JSON schema field "wait_until".
	WaitUntil *LoadState `json:"wait_until,omitempty"`
}

type PageRef struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Title corresponds to the JSON schema field "title".
	Title *string `json:"title,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty"`
}

type PageReloadOptions struct {
	// IgnoreCache corresponds to the JSON schema field "ignore_cache".
	IgnoreCache *bool `json:"ignore_cache,omitempty"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout *int `json:"timeout,omitempty"`

	// WaitUntil corresponds to the JSON schema field "wait_until".
	WaitUntil *LoadState `json:"wait_until,omitempty"`
}

type PageReloadParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageReloadOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageScreenshotClip struct {
	// Height corresponds to the JSON schema field "height".
	Height float64 `json:"height"`

	// Width corresponds to the JSON schema field "width".
	Width float64 `json:"width"`

	// X corresponds to the JSON schema field "x".
	X float64 `json:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y"`
}

type PageScreenshotOptions struct {
	// Animations corresponds to the JSON schema field "animations".
	Animations *PageScreenshotOptionsAnimations `json:"animations,omitempty"`

	// Caret corresponds to the JSON schema field "caret".
	Caret *PageScreenshotOptionsCaret `json:"caret,omitempty"`

	// Clip corresponds to the JSON schema field "clip".
	Clip *PageScreenshotClip `json:"clip,omitempty"`

	// FullPage corresponds to the JSON schema field "full_page".
	FullPage *bool `json:"full_page,omitempty"`

	// Mask corresponds to the JSON schema field "mask".
	Mask []LocatorDescriptor `json:"mask,omitempty"`

	// MaskColor corresponds to the JSON schema field "mask_color".
	MaskColor *string `json:"mask_color,omitempty"`

	// OmitBackground corresponds to the JSON schema field "omit_background".
	OmitBackground *bool `json:"omit_background,omitempty"`

	// Quality corresponds to the JSON schema field "quality".
	Quality *int `json:"quality,omitempty"`

	// Scale corresponds to the JSON schema field "scale".
	Scale *PageScreenshotOptionsScale `json:"scale,omitempty"`

	// Style corresponds to the JSON schema field "style".
	Style *string `json:"style,omitempty"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout *float64 `json:"timeout,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *PageScreenshotOptionsType `json:"type,omitempty"`
}

type PageScreenshotOptionsAnimations string

const PageScreenshotOptionsAnimationsAllow PageScreenshotOptionsAnimations = "allow"
const PageScreenshotOptionsAnimationsDisabled PageScreenshotOptionsAnimations = "disabled"

type PageScreenshotOptionsCaret string

const PageScreenshotOptionsCaretHide PageScreenshotOptionsCaret = "hide"
const PageScreenshotOptionsCaretInitial PageScreenshotOptionsCaret = "initial"

type PageScreenshotOptionsScale string

const PageScreenshotOptionsScaleCSS PageScreenshotOptionsScale = "css"
const PageScreenshotOptionsScaleDevice PageScreenshotOptionsScale = "device"

type PageScreenshotOptionsType string

const PageScreenshotOptionsTypeJPEG PageScreenshotOptionsType = "jpeg"
const PageScreenshotOptionsTypePNG PageScreenshotOptionsType = "png"

type PageScreenshotParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageScreenshotOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageScreenshotResult struct {
	// Data corresponds to the JSON schema field "data".
	Data string `json:"data"`

	// Type corresponds to the JSON schema field "type".
	Type PageScreenshotResultType `json:"type"`
}

type PageScreenshotResultType string

const PageScreenshotResultTypeJPEG PageScreenshotResultType = "jpeg"
const PageScreenshotResultTypePNG PageScreenshotResultType = "png"

type PageScrollOptions struct {
	// ReturnXPath corresponds to the JSON schema field "return_xpath".
	ReturnXPath *bool `json:"return_xpath,omitempty"`
}

type PageScrollParams struct {
	// DeltaX corresponds to the JSON schema field "delta_x".
	DeltaX float64 `json:"delta_x"`

	// DeltaY corresponds to the JSON schema field "delta_y".
	DeltaY float64 `json:"delta_y"`

	// Options corresponds to the JSON schema field "options".
	Options *PageScrollOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// X corresponds to the JSON schema field "x".
	X float64 `json:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y"`
}

type PageSetExtraHTTPHeadersParams struct {
	// Headers corresponds to the JSON schema field "headers".
	Headers PageSetExtraHTTPHeadersParamsHeaders `json:"headers"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageSetExtraHTTPHeadersParamsHeaders map[string]string

type PageSetViewportSizeOptions struct {
	// DeviceScaleFactor corresponds to the JSON schema field "device_scale_factor".
	DeviceScaleFactor *float64 `json:"device_scale_factor,omitempty"`
}

type PageSetViewportSizeParams struct {
	// Height corresponds to the JSON schema field "height".
	Height int `json:"height"`

	// Options corresponds to the JSON schema field "options".
	Options *PageSetViewportSizeOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Width corresponds to the JSON schema field "width".
	Width int `json:"width"`
}

type PageSnapshotOptions struct {
	// IncludeIframes corresponds to the JSON schema field "include_iframes".
	IncludeIframes *bool `json:"include_iframes,omitempty"`
}

type PageSnapshotParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageSnapshotOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type PageTitleResult struct {
	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`
}

type PageTypeOptions struct {
	// Delay corresponds to the JSON schema field "delay".
	Delay *float64 `json:"delay,omitempty"`

	// WithMistakes corresponds to the JSON schema field "with_mistakes".
	WithMistakes *bool `json:"with_mistakes,omitempty"`
}

type PageTypeParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageTypeOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`
}

type PageURLResult struct {
	// URL corresponds to the JSON schema field "url".
	URL string `json:"url"`
}

type PageVoidResult struct {
	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`
}

type PageWaitForLoadStateParams struct {
	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// State corresponds to the JSON schema field "state".
	State LoadState `json:"state"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout *int `json:"timeout,omitempty"`
}

type PageWaitForSelectorOptions struct {
	// PierceShadow corresponds to the JSON schema field "pierce_shadow".
	PierceShadow *bool `json:"pierce_shadow,omitempty"`

	// State corresponds to the JSON schema field "state".
	State *PageWaitForSelectorOptionsState `json:"state,omitempty"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout *int `json:"timeout,omitempty"`
}

type PageWaitForSelectorOptionsState string

const PageWaitForSelectorOptionsStateAttached PageWaitForSelectorOptionsState = "attached"
const PageWaitForSelectorOptionsStateDetached PageWaitForSelectorOptionsState = "detached"
const PageWaitForSelectorOptionsStateHidden PageWaitForSelectorOptionsState = "hidden"
const PageWaitForSelectorOptionsStateVisible PageWaitForSelectorOptionsState = "visible"

type PageWaitForSelectorParams struct {
	// Options corresponds to the JSON schema field "options".
	Options *PageWaitForSelectorOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Selector corresponds to the JSON schema field "selector".
	Selector string `json:"selector"`
}

type PageWaitForSelectorResult struct {
	// Matched corresponds to the JSON schema field "matched".
	Matched bool `json:"matched"`
}

type PageWaitForTimeoutParams struct {
	// Ms corresponds to the JSON schema field "ms".
	Ms int `json:"ms"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type RgbaColor struct {
	// A corresponds to the JSON schema field "a".
	A *float64 `json:"a,omitempty"`

	// B corresponds to the JSON schema field "b".
	B float64 `json:"b"`

	// G corresponds to the JSON schema field "g".
	G float64 `json:"g"`

	// R corresponds to the JSON schema field "r".
	R float64 `json:"r"`
}

type RuntimeConfigureParams struct {
	// CDPURL corresponds to the JSON schema field "cdp_url".
	CDPURL string `json:"cdp_url"`

	// ClientInfo corresponds to the JSON schema field "client_info".
	ClientInfo *ImplementationInfo `json:"client_info,omitempty"`

	// LogLevel corresponds to the JSON schema field "log_level".
	LogLevel RuntimeConfigureParamsLogLevel `json:"log_level,omitempty"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion *int `json:"protocol_version,omitempty"`

	// Telemetry corresponds to the JSON schema field "telemetry".
	Telemetry *TelemetryConfig `json:"telemetry,omitempty"`
}

type RuntimeConfigureParamsLogLevel string

const RuntimeConfigureParamsLogLevelDebug RuntimeConfigureParamsLogLevel = "debug"
const RuntimeConfigureParamsLogLevelError RuntimeConfigureParamsLogLevel = "error"
const RuntimeConfigureParamsLogLevelInfo RuntimeConfigureParamsLogLevel = "info"
const RuntimeConfigureParamsLogLevelOff RuntimeConfigureParamsLogLevel = "off"
const RuntimeConfigureParamsLogLevelWarn RuntimeConfigureParamsLogLevel = "warn"

type RuntimeConfigureResult struct {
	// Configured corresponds to the JSON schema field "configured".
	Configured bool `json:"configured"`
}

type RuntimeLoopbackStatusResult struct {
	// Configured corresponds to the JSON schema field "configured".
	Configured bool `json:"configured"`

	// Connected corresponds to the JSON schema field "connected".
	Connected bool `json:"connected"`
}

type SnapshotResult struct {
	// FormattedTree corresponds to the JSON schema field "formatted_tree".
	FormattedTree string `json:"formatted_tree"`

	// URLMap corresponds to the JSON schema field "url_map".
	URLMap SnapshotResultURLMap `json:"url_map"`

	// XPathMap corresponds to the JSON schema field "xpath_map".
	XPathMap SnapshotResultXPathMap `json:"xpath_map"`
}

type SnapshotResultURLMap map[string]string

type SnapshotResultXPathMap map[string]string

type StagehandActParams struct {
	// Input corresponds to the JSON schema field "input".
	Input string `json:"input"`

	// Options corresponds to the JSON schema field "options".
	Options *ActOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type StagehandCloseResult struct {
	// Closed corresponds to the JSON schema field "closed".
	Closed bool `json:"closed"`
}

type StagehandExtractParams struct {
	// Instruction corresponds to the JSON schema field "instruction".
	Instruction string `json:"instruction"`

	// Options corresponds to the JSON schema field "options".
	Options *ExtractOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`

	// Schema corresponds to the JSON schema field "schema".
	Schema json.RawMessage `json:"schema"`
}

type StagehandInitParams struct {
	// APIKey corresponds to the JSON schema field "api_key".
	APIKey *string `json:"api_key,omitempty"`

	// Browser corresponds to the JSON schema field "browser".
	Browser *BrowserbaseBrowserSource `json:"browser,omitempty"`

	// Cache corresponds to the JSON schema field "cache".
	Cache *Caching `json:"cache,omitempty"`

	// DOMSettleTimeoutMs corresponds to the JSON schema field
	// "dom_settle_timeout_ms".
	DOMSettleTimeoutMs *int `json:"dom_settle_timeout_ms,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *StagehandInitModel `json:"model,omitempty"`

	// SelfHeal corresponds to the JSON schema field "self_heal".
	SelfHeal *bool `json:"self_heal,omitempty"`

	// SystemPrompt corresponds to the JSON schema field "system_prompt".
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Telemetry corresponds to the JSON schema field "telemetry".
	Telemetry *TelemetryConfig `json:"telemetry,omitempty"`
}

type StagehandInitResult struct {
	// Initialized corresponds to the JSON schema field "initialized".
	Initialized bool `json:"initialized"`

	// Pages corresponds to the JSON schema field "pages".
	Pages []PageRef `json:"pages"`
}

type StagehandLog struct {
	// Data corresponds to the JSON schema field "data".
	Data StagehandLogData `json:"data"`

	// Level corresponds to the JSON schema field "level".
	Level StagehandLogLevel `json:"level"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

type StagehandLogData map[string]json.RawMessage

type StagehandLogLevel string

const StagehandLogLevelDebug StagehandLogLevel = "debug"
const StagehandLogLevelError StagehandLogLevel = "error"
const StagehandLogLevelInfo StagehandLogLevel = "info"
const StagehandLogLevelWarn StagehandLogLevel = "warn"

type StagehandMetrics struct {
	// ActCachedInputTokens corresponds to the JSON schema field
	// "act_cached_input_tokens".
	ActCachedInputTokens float64 `json:"act_cached_input_tokens"`

	// ActCompletionTokens corresponds to the JSON schema field
	// "act_completion_tokens".
	ActCompletionTokens float64 `json:"act_completion_tokens"`

	// ActInferenceTimeMs corresponds to the JSON schema field
	// "act_inference_time_ms".
	ActInferenceTimeMs float64 `json:"act_inference_time_ms"`

	// ActPromptTokens corresponds to the JSON schema field "act_prompt_tokens".
	ActPromptTokens float64 `json:"act_prompt_tokens"`

	// ActReasoningTokens corresponds to the JSON schema field "act_reasoning_tokens".
	ActReasoningTokens float64 `json:"act_reasoning_tokens"`

	// ExtractCachedInputTokens corresponds to the JSON schema field
	// "extract_cached_input_tokens".
	ExtractCachedInputTokens float64 `json:"extract_cached_input_tokens"`

	// ExtractCompletionTokens corresponds to the JSON schema field
	// "extract_completion_tokens".
	ExtractCompletionTokens float64 `json:"extract_completion_tokens"`

	// ExtractInferenceTimeMs corresponds to the JSON schema field
	// "extract_inference_time_ms".
	ExtractInferenceTimeMs float64 `json:"extract_inference_time_ms"`

	// ExtractPromptTokens corresponds to the JSON schema field
	// "extract_prompt_tokens".
	ExtractPromptTokens float64 `json:"extract_prompt_tokens"`

	// ExtractReasoningTokens corresponds to the JSON schema field
	// "extract_reasoning_tokens".
	ExtractReasoningTokens float64 `json:"extract_reasoning_tokens"`

	// ObserveCachedInputTokens corresponds to the JSON schema field
	// "observe_cached_input_tokens".
	ObserveCachedInputTokens float64 `json:"observe_cached_input_tokens"`

	// ObserveCompletionTokens corresponds to the JSON schema field
	// "observe_completion_tokens".
	ObserveCompletionTokens float64 `json:"observe_completion_tokens"`

	// ObserveInferenceTimeMs corresponds to the JSON schema field
	// "observe_inference_time_ms".
	ObserveInferenceTimeMs float64 `json:"observe_inference_time_ms"`

	// ObservePromptTokens corresponds to the JSON schema field
	// "observe_prompt_tokens".
	ObservePromptTokens float64 `json:"observe_prompt_tokens"`

	// ObserveReasoningTokens corresponds to the JSON schema field
	// "observe_reasoning_tokens".
	ObserveReasoningTokens float64 `json:"observe_reasoning_tokens"`

	// TotalCachedInputTokens corresponds to the JSON schema field
	// "total_cached_input_tokens".
	TotalCachedInputTokens float64 `json:"total_cached_input_tokens"`

	// TotalCompletionTokens corresponds to the JSON schema field
	// "total_completion_tokens".
	TotalCompletionTokens float64 `json:"total_completion_tokens"`

	// TotalInferenceTimeMs corresponds to the JSON schema field
	// "total_inference_time_ms".
	TotalInferenceTimeMs float64 `json:"total_inference_time_ms"`

	// TotalPromptTokens corresponds to the JSON schema field "total_prompt_tokens".
	TotalPromptTokens float64 `json:"total_prompt_tokens"`

	// TotalReasoningTokens corresponds to the JSON schema field
	// "total_reasoning_tokens".
	TotalReasoningTokens float64 `json:"total_reasoning_tokens"`
}

type StagehandObserveParams struct {
	// Instruction corresponds to the JSON schema field "instruction".
	Instruction *string `json:"instruction,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *ObserveOptions `json:"options,omitempty"`

	// PageID corresponds to the JSON schema field "page_id".
	PageID string `json:"page_id"`
}

type StagehandPingResult struct {
	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime string `json:"runtime"`
}

type TelemetryConfig struct {
	// Traces corresponds to the JSON schema field "traces".
	Traces TelemetryTraces `json:"traces"`
}

type TelemetryTraces struct {
	// Endpoint corresponds to the JSON schema field "endpoint".
	Endpoint string `json:"endpoint"`

	// Headers corresponds to the JSON schema field "headers".
	Headers TelemetryTracesHeaders `json:"headers,omitempty"`
}

type TelemetryTracesHeaders map[string]string

type Variables map[string]VariableValue

type generatedModelCatalog struct {
	// ActOptions corresponds to the JSON schema field "ActOptions".
	ActOptions *ActOptions `json:"ActOptions,omitempty"`

	// ActResult corresponds to the JSON schema field "ActResult".
	ActResult *ActResult `json:"ActResult,omitempty"`

	// ActResultData corresponds to the JSON schema field "ActResultData".
	ActResultData *ActResultData `json:"ActResultData,omitempty"`

	// Action corresponds to the JSON schema field "Action".
	Action *Action `json:"Action,omitempty"`

	// AnthropicModelName corresponds to the JSON schema field "AnthropicModelName".
	AnthropicModelName *AnthropicModelName `json:"AnthropicModelName,omitempty"`

	// BrowserGetVersionResult corresponds to the JSON schema field
	// "BrowserGetVersionResult".
	BrowserGetVersionResult *BrowserGetVersionResult `json:"BrowserGetVersionResult,omitempty"`

	// BrowserbaseBrowserSettings corresponds to the JSON schema field
	// "BrowserbaseBrowserSettings".
	BrowserbaseBrowserSettings *BrowserbaseBrowserSettings `json:"BrowserbaseBrowserSettings,omitempty"`

	// BrowserbaseBrowserSource corresponds to the JSON schema field
	// "BrowserbaseBrowserSource".
	BrowserbaseBrowserSource *BrowserbaseBrowserSource `json:"BrowserbaseBrowserSource,omitempty"`

	// BrowserbaseContext corresponds to the JSON schema field "BrowserbaseContext".
	BrowserbaseContext *BrowserbaseContext `json:"BrowserbaseContext,omitempty"`

	// BrowserbaseFingerprint corresponds to the JSON schema field
	// "BrowserbaseFingerprint".
	BrowserbaseFingerprint *BrowserbaseFingerprint `json:"BrowserbaseFingerprint,omitempty"`

	// BrowserbaseFingerprintScreen corresponds to the JSON schema field
	// "BrowserbaseFingerprintScreen".
	BrowserbaseFingerprintScreen *BrowserbaseFingerprintScreen `json:"BrowserbaseFingerprintScreen,omitempty"`

	// BrowserbaseProxyConfig corresponds to the JSON schema field
	// "BrowserbaseProxyConfig".
	BrowserbaseProxyConfig *BrowserbaseProxyConfig `json:"BrowserbaseProxyConfig,omitempty"`

	// BrowserbaseProxyGeolocation corresponds to the JSON schema field
	// "BrowserbaseProxyGeolocation".
	BrowserbaseProxyGeolocation *BrowserbaseProxyGeolocation `json:"BrowserbaseProxyGeolocation,omitempty"`

	// BrowserbaseRegion corresponds to the JSON schema field "BrowserbaseRegion".
	BrowserbaseRegion *BrowserbaseRegion `json:"BrowserbaseRegion,omitempty"`

	// BrowserbaseViewport corresponds to the JSON schema field "BrowserbaseViewport".
	BrowserbaseViewport *BrowserbaseViewport `json:"BrowserbaseViewport,omitempty"`

	// CacheStatus corresponds to the JSON schema field "CacheStatus".
	CacheStatus *CacheStatus `json:"CacheStatus,omitempty"`

	// Caching corresponds to the JSON schema field "Caching".
	Caching *Caching `json:"Caching,omitempty"`

	// CerebrasModelName corresponds to the JSON schema field "CerebrasModelName".
	CerebrasModelName *CerebrasModelName `json:"CerebrasModelName,omitempty"`

	// ClearCookieOptions corresponds to the JSON schema field "ClearCookieOptions".
	ClearCookieOptions *ClearCookieOptions `json:"ClearCookieOptions,omitempty"`

	// ClientModelReference corresponds to the JSON schema field
	// "ClientModelReference".
	ClientModelReference *ClientModelReference `json:"ClientModelReference,omitempty"`

	// ContextActivePageResult corresponds to the JSON schema field
	// "ContextActivePageResult".
	ContextActivePageResult *ContextActivePageResult `json:"ContextActivePageResult,omitempty"`

	// ContextAddCookiesParams corresponds to the JSON schema field
	// "ContextAddCookiesParams".
	ContextAddCookiesParams *ContextAddCookiesParams `json:"ContextAddCookiesParams,omitempty"`

	// ContextAddInitScriptParams corresponds to the JSON schema field
	// "ContextAddInitScriptParams".
	ContextAddInitScriptParams *ContextAddInitScriptParams `json:"ContextAddInitScriptParams,omitempty"`

	// ContextClearCookiesParams corresponds to the JSON schema field
	// "ContextClearCookiesParams".
	ContextClearCookiesParams *ContextClearCookiesParams `json:"ContextClearCookiesParams,omitempty"`

	// ContextClipboardPasteParams corresponds to the JSON schema field
	// "ContextClipboardPasteParams".
	ContextClipboardPasteParams *ContextClipboardPasteParams `json:"ContextClipboardPasteParams,omitempty"`

	// ContextClipboardReadTextResult corresponds to the JSON schema field
	// "ContextClipboardReadTextResult".
	ContextClipboardReadTextResult *ContextClipboardReadTextResult `json:"ContextClipboardReadTextResult,omitempty"`

	// ContextClipboardTarget corresponds to the JSON schema field
	// "ContextClipboardTarget".
	ContextClipboardTarget *ContextClipboardTarget `json:"ContextClipboardTarget,omitempty"`

	// ContextClipboardWriteTextParams corresponds to the JSON schema field
	// "ContextClipboardWriteTextParams".
	ContextClipboardWriteTextParams *ContextClipboardWriteTextParams `json:"ContextClipboardWriteTextParams,omitempty"`

	// ContextCloseResult corresponds to the JSON schema field "ContextCloseResult".
	ContextCloseResult *ContextCloseResult `json:"ContextCloseResult,omitempty"`

	// ContextCookiesParams corresponds to the JSON schema field
	// "ContextCookiesParams".
	ContextCookiesParams *ContextCookiesParams `json:"ContextCookiesParams,omitempty"`

	// ContextCookiesResult corresponds to the JSON schema field
	// "ContextCookiesResult".
	ContextCookiesResult *ContextCookiesResult `json:"ContextCookiesResult,omitempty"`

	// ContextGetDomainPolicyResult corresponds to the JSON schema field
	// "ContextGetDomainPolicyResult".
	ContextGetDomainPolicyResult *ContextGetDomainPolicyResult `json:"ContextGetDomainPolicyResult,omitempty"`

	// ContextNewPageParams corresponds to the JSON schema field
	// "ContextNewPageParams".
	ContextNewPageParams *ContextNewPageParams `json:"ContextNewPageParams,omitempty"`

	// ContextPagesResult corresponds to the JSON schema field "ContextPagesResult".
	ContextPagesResult ContextPagesResult `json:"ContextPagesResult,omitempty"`

	// ContextSetActivePageParams corresponds to the JSON schema field
	// "ContextSetActivePageParams".
	ContextSetActivePageParams *ContextSetActivePageParams `json:"ContextSetActivePageParams,omitempty"`

	// ContextSetDomainPolicyParams corresponds to the JSON schema field
	// "ContextSetDomainPolicyParams".
	ContextSetDomainPolicyParams *ContextSetDomainPolicyParams `json:"ContextSetDomainPolicyParams,omitempty"`

	// ContextSetExtraHTTPHeadersParams corresponds to the JSON schema field
	// "ContextSetExtraHTTPHeadersParams".
	ContextSetExtraHTTPHeadersParams *ContextSetExtraHTTPHeadersParams `json:"ContextSetExtraHTTPHeadersParams,omitempty"`

	// ContextVoidResult corresponds to the JSON schema field "ContextVoidResult".
	ContextVoidResult *ContextVoidResult `json:"ContextVoidResult,omitempty"`

	// Cookie corresponds to the JSON schema field "Cookie".
	Cookie *Cookie `json:"Cookie,omitempty"`

	// CookieFilter corresponds to the JSON schema field "CookieFilter".
	CookieFilter *CookieFilter `json:"CookieFilter,omitempty"`

	// CookieParam corresponds to the JSON schema field "CookieParam".
	CookieParam *CookieParam `json:"CookieParam,omitempty"`

	// CookieRegex corresponds to the JSON schema field "CookieRegex".
	CookieRegex *CookieRegex `json:"CookieRegex,omitempty"`

	// CustomModelConfig corresponds to the JSON schema field "CustomModelConfig".
	CustomModelConfig *CustomModelConfig `json:"CustomModelConfig,omitempty"`

	// DescribedVariableValue corresponds to the JSON schema field
	// "DescribedVariableValue".
	DescribedVariableValue *DescribedVariableValue `json:"DescribedVariableValue,omitempty"`

	// DomainPolicy corresponds to the JSON schema field "DomainPolicy".
	DomainPolicy *DomainPolicy `json:"DomainPolicy,omitempty"`

	// EmptyParams corresponds to the JSON schema field "EmptyParams".
	EmptyParams *EmptyParams `json:"EmptyParams,omitempty"`

	// ExternalProxyConfig corresponds to the JSON schema field "ExternalProxyConfig".
	ExternalProxyConfig *ExternalProxyConfig `json:"ExternalProxyConfig,omitempty"`

	// ExtractOptions corresponds to the JSON schema field "ExtractOptions".
	ExtractOptions *ExtractOptions `json:"ExtractOptions,omitempty"`

	// ExtractResult corresponds to the JSON schema field "ExtractResult".
	ExtractResult *ExtractResult `json:"ExtractResult,omitempty"`

	// GoogleModelName corresponds to the JSON schema field "GoogleModelName".
	GoogleModelName *GoogleModelName `json:"GoogleModelName,omitempty"`

	// GroqModelName corresponds to the JSON schema field "GroqModelName".
	GroqModelName *GroqModelName `json:"GroqModelName,omitempty"`

	// ImplementationInfo corresponds to the JSON schema field "ImplementationInfo".
	ImplementationInfo *ImplementationInfo `json:"ImplementationInfo,omitempty"`

	// KnownModelConfig corresponds to the JSON schema field "KnownModelConfig".
	KnownModelConfig *KnownModelConfig `json:"KnownModelConfig,omitempty"`

	// LLMAnnotations corresponds to the JSON schema field "LLMAnnotations".
	LLMAnnotations *LLMAnnotations `json:"LLMAnnotations,omitempty"`

	// LLMClientTool corresponds to the JSON schema field "LLMClientTool".
	LLMClientTool *LLMClientTool `json:"LLMClientTool,omitempty"`

	// LLMGenerateParams corresponds to the JSON schema field "LLMGenerateParams".
	LLMGenerateParams *LLMGenerateParams `json:"LLMGenerateParams,omitempty"`

	// LLMGenerateResult corresponds to the JSON schema field "LLMGenerateResult".
	LLMGenerateResult *LLMGenerateResult `json:"LLMGenerateResult,omitempty"`

	// LLMImageContent corresponds to the JSON schema field "LLMImageContent".
	LLMImageContent *LLMImageContent `json:"LLMImageContent,omitempty"`

	// LLMJsonSchemaResponseFormat corresponds to the JSON schema field
	// "LLMJsonSchemaResponseFormat".
	LLMJsonSchemaResponseFormat *LLMJSONSchemaResponseFormat `json:"LLMJsonSchemaResponseFormat,omitempty"`

	// LLMMessage corresponds to the JSON schema field "LLMMessage".
	LLMMessage *LLMMessage `json:"LLMMessage,omitempty"`

	// LLMMessageContentBlock corresponds to the JSON schema field
	// "LLMMessageContentBlock".
	LLMMessageContentBlock *LLMMessageContentBlock `json:"LLMMessageContentBlock,omitempty"`

	// LLMMessageGenerateParams corresponds to the JSON schema field
	// "LLMMessageGenerateParams".
	LLMMessageGenerateParams *LLMMessageGenerateParams `json:"LLMMessageGenerateParams,omitempty"`

	// LLMMessageGenerateResult corresponds to the JSON schema field
	// "LLMMessageGenerateResult".
	LLMMessageGenerateResult *LLMMessageGenerateResult `json:"LLMMessageGenerateResult,omitempty"`

	// LLMRole corresponds to the JSON schema field "LLMRole".
	LLMRole *LLMRole `json:"LLMRole,omitempty"`

	// LLMStructuredGenerateParams corresponds to the JSON schema field
	// "LLMStructuredGenerateParams".
	LLMStructuredGenerateParams *LLMStructuredGenerateParams `json:"LLMStructuredGenerateParams,omitempty"`

	// LLMStructuredGenerateResult corresponds to the JSON schema field
	// "LLMStructuredGenerateResult".
	LLMStructuredGenerateResult *LLMStructuredGenerateResult `json:"LLMStructuredGenerateResult,omitempty"`

	// LLMTextContent corresponds to the JSON schema field "LLMTextContent".
	LLMTextContent *LLMTextContent `json:"LLMTextContent,omitempty"`

	// LLMTextResponseFormat corresponds to the JSON schema field
	// "LLMTextResponseFormat".
	LLMTextResponseFormat *LLMTextResponseFormat `json:"LLMTextResponseFormat,omitempty"`

	// LLMToolAnnotations corresponds to the JSON schema field "LLMToolAnnotations".
	LLMToolAnnotations *LLMToolAnnotations `json:"LLMToolAnnotations,omitempty"`

	// LLMToolChoice corresponds to the JSON schema field "LLMToolChoice".
	LLMToolChoice *LLMToolChoice `json:"LLMToolChoice,omitempty"`

	// LLMToolExecution corresponds to the JSON schema field "LLMToolExecution".
	LLMToolExecution *LLMToolExecution `json:"LLMToolExecution,omitempty"`

	// LLMToolIcon corresponds to the JSON schema field "LLMToolIcon".
	LLMToolIcon *LLMToolIcon `json:"LLMToolIcon,omitempty"`

	// LLMToolJSON corresponds to the JSON schema field "LLMToolJson".
	LLMToolJSON *LLMToolJSON `json:"LLMToolJson,omitempty"`

	// LLMToolResultContent corresponds to the JSON schema field
	// "LLMToolResultContent".
	LLMToolResultContent *LLMToolResultContent `json:"LLMToolResultContent,omitempty"`

	// LLMToolResultContentBlock corresponds to the JSON schema field
	// "LLMToolResultContentBlock".
	LLMToolResultContentBlock *LLMToolResultContentBlock `json:"LLMToolResultContentBlock,omitempty"`

	// LLMToolUseContent corresponds to the JSON schema field "LLMToolUseContent".
	LLMToolUseContent *LLMToolUseContent `json:"LLMToolUseContent,omitempty"`

	// LLMUsage corresponds to the JSON schema field "LLMUsage".
	LLMUsage *LLMUsage `json:"LLMUsage,omitempty"`

	// LoadState corresponds to the JSON schema field "LoadState".
	LoadState *LoadState `json:"LoadState,omitempty"`

	// Locator corresponds to the JSON schema field "Locator".
	Locator *Locator `json:"Locator,omitempty"`

	// LocatorCentroidResult corresponds to the JSON schema field
	// "LocatorCentroidResult".
	LocatorCentroidResult *LocatorCentroidResult `json:"LocatorCentroidResult,omitempty"`

	// LocatorClickOptions corresponds to the JSON schema field "LocatorClickOptions".
	LocatorClickOptions *LocatorClickOptions `json:"LocatorClickOptions,omitempty"`

	// LocatorClickParams corresponds to the JSON schema field "LocatorClickParams".
	LocatorClickParams *LocatorClickParams `json:"LocatorClickParams,omitempty"`

	// LocatorClickResult corresponds to the JSON schema field "LocatorClickResult".
	LocatorClickResult *LocatorClickResult `json:"LocatorClickResult,omitempty"`

	// LocatorCountResult corresponds to the JSON schema field "LocatorCountResult".
	LocatorCountResult *LocatorCountResult `json:"LocatorCountResult,omitempty"`

	// LocatorDescriptor corresponds to the JSON schema field "LocatorDescriptor".
	LocatorDescriptor *LocatorDescriptor `json:"LocatorDescriptor,omitempty"`

	// LocatorFillParams corresponds to the JSON schema field "LocatorFillParams".
	LocatorFillParams *LocatorFillParams `json:"LocatorFillParams,omitempty"`

	// LocatorFillResult corresponds to the JSON schema field "LocatorFillResult".
	LocatorFillResult *LocatorFillResult `json:"LocatorFillResult,omitempty"`

	// LocatorHighlightOptions corresponds to the JSON schema field
	// "LocatorHighlightOptions".
	LocatorHighlightOptions *LocatorHighlightOptions `json:"LocatorHighlightOptions,omitempty"`

	// LocatorHighlightParams corresponds to the JSON schema field
	// "LocatorHighlightParams".
	LocatorHighlightParams *LocatorHighlightParams `json:"LocatorHighlightParams,omitempty"`

	// LocatorHighlightResult corresponds to the JSON schema field
	// "LocatorHighlightResult".
	LocatorHighlightResult *LocatorHighlightResult `json:"LocatorHighlightResult,omitempty"`

	// LocatorHoverResult corresponds to the JSON schema field "LocatorHoverResult".
	LocatorHoverResult *LocatorHoverResult `json:"LocatorHoverResult,omitempty"`

	// LocatorInnerHTMLResult corresponds to the JSON schema field
	// "LocatorInnerHtmlResult".
	LocatorInnerHTMLResult *LocatorInnerHTMLResult `json:"LocatorInnerHtmlResult,omitempty"`

	// LocatorInnerTextResult corresponds to the JSON schema field
	// "LocatorInnerTextResult".
	LocatorInnerTextResult *LocatorInnerTextResult `json:"LocatorInnerTextResult,omitempty"`

	// LocatorInputValueResult corresponds to the JSON schema field
	// "LocatorInputValueResult".
	LocatorInputValueResult *LocatorInputValueResult `json:"LocatorInputValueResult,omitempty"`

	// LocatorIsCheckedResult corresponds to the JSON schema field
	// "LocatorIsCheckedResult".
	LocatorIsCheckedResult *LocatorIsCheckedResult `json:"LocatorIsCheckedResult,omitempty"`

	// LocatorIsVisibleResult corresponds to the JSON schema field
	// "LocatorIsVisibleResult".
	LocatorIsVisibleResult *LocatorIsVisibleResult `json:"LocatorIsVisibleResult,omitempty"`

	// LocatorScrollToParams corresponds to the JSON schema field
	// "LocatorScrollToParams".
	LocatorScrollToParams *LocatorScrollToParams `json:"LocatorScrollToParams,omitempty"`

	// LocatorScrollToResult corresponds to the JSON schema field
	// "LocatorScrollToResult".
	LocatorScrollToResult *LocatorScrollToResult `json:"LocatorScrollToResult,omitempty"`

	// LocatorSelectOptionParams corresponds to the JSON schema field
	// "LocatorSelectOptionParams".
	LocatorSelectOptionParams *LocatorSelectOptionParams `json:"LocatorSelectOptionParams,omitempty"`

	// LocatorSelectOptionResult corresponds to the JSON schema field
	// "LocatorSelectOptionResult".
	LocatorSelectOptionResult *LocatorSelectOptionResult `json:"LocatorSelectOptionResult,omitempty"`

	// LocatorSendClickEventOptions corresponds to the JSON schema field
	// "LocatorSendClickEventOptions".
	LocatorSendClickEventOptions *LocatorSendClickEventOptions `json:"LocatorSendClickEventOptions,omitempty"`

	// LocatorSendClickEventParams corresponds to the JSON schema field
	// "LocatorSendClickEventParams".
	LocatorSendClickEventParams *LocatorSendClickEventParams `json:"LocatorSendClickEventParams,omitempty"`

	// LocatorSendClickEventResult corresponds to the JSON schema field
	// "LocatorSendClickEventResult".
	LocatorSendClickEventResult *LocatorSendClickEventResult `json:"LocatorSendClickEventResult,omitempty"`

	// LocatorTextContentResult corresponds to the JSON schema field
	// "LocatorTextContentResult".
	LocatorTextContentResult *LocatorTextContentResult `json:"LocatorTextContentResult,omitempty"`

	// LocatorTypeOptions corresponds to the JSON schema field "LocatorTypeOptions".
	LocatorTypeOptions *LocatorTypeOptions `json:"LocatorTypeOptions,omitempty"`

	// LocatorTypeParams corresponds to the JSON schema field "LocatorTypeParams".
	LocatorTypeParams *LocatorTypeParams `json:"LocatorTypeParams,omitempty"`

	// LocatorTypeResult corresponds to the JSON schema field "LocatorTypeResult".
	LocatorTypeResult *LocatorTypeResult `json:"LocatorTypeResult,omitempty"`

	// ModelConfig corresponds to the JSON schema field "ModelConfig".
	ModelConfig *ModelConfig `json:"ModelConfig,omitempty"`

	// ModelName corresponds to the JSON schema field "ModelName".
	ModelName *ModelName `json:"ModelName,omitempty"`

	// MouseButton corresponds to the JSON schema field "MouseButton".
	MouseButton *MouseButton `json:"MouseButton,omitempty"`

	// ObserveOptions corresponds to the JSON schema field "ObserveOptions".
	ObserveOptions *ObserveOptions `json:"ObserveOptions,omitempty"`

	// ObserveResult corresponds to the JSON schema field "ObserveResult".
	ObserveResult *ObserveResult `json:"ObserveResult,omitempty"`

	// OpenAIModelName corresponds to the JSON schema field "OpenAIModelName".
	OpenAIModelName *OpenAIModelName `json:"OpenAIModelName,omitempty"`

	// PageAddInitScriptParams corresponds to the JSON schema field
	// "PageAddInitScriptParams".
	PageAddInitScriptParams *PageAddInitScriptParams `json:"PageAddInitScriptParams,omitempty"`

	// PageClickOptions corresponds to the JSON schema field "PageClickOptions".
	PageClickOptions *PageClickOptions `json:"PageClickOptions,omitempty"`

	// PageClickParams corresponds to the JSON schema field "PageClickParams".
	PageClickParams *PageClickParams `json:"PageClickParams,omitempty"`

	// PageCloseResult corresponds to the JSON schema field "PageCloseResult".
	PageCloseResult *PageCloseResult `json:"PageCloseResult,omitempty"`

	// PageCoordinateResult corresponds to the JSON schema field
	// "PageCoordinateResult".
	PageCoordinateResult *PageCoordinateResult `json:"PageCoordinateResult,omitempty"`

	// PageDragAndDropOptions corresponds to the JSON schema field
	// "PageDragAndDropOptions".
	PageDragAndDropOptions *PageDragAndDropOptions `json:"PageDragAndDropOptions,omitempty"`

	// PageDragAndDropParams corresponds to the JSON schema field
	// "PageDragAndDropParams".
	PageDragAndDropParams *PageDragAndDropParams `json:"PageDragAndDropParams,omitempty"`

	// PageDragAndDropResult corresponds to the JSON schema field
	// "PageDragAndDropResult".
	PageDragAndDropResult *PageDragAndDropResult `json:"PageDragAndDropResult,omitempty"`

	// PageEvaluateParams corresponds to the JSON schema field "PageEvaluateParams".
	PageEvaluateParams *PageEvaluateParams `json:"PageEvaluateParams,omitempty"`

	// PageEvaluateResult corresponds to the JSON schema field "PageEvaluateResult".
	PageEvaluateResult *PageEvaluateResult `json:"PageEvaluateResult,omitempty"`

	// PageGoBackParams corresponds to the JSON schema field "PageGoBackParams".
	PageGoBackParams *PageGoBackParams `json:"PageGoBackParams,omitempty"`

	// PageGoForwardParams corresponds to the JSON schema field "PageGoForwardParams".
	PageGoForwardParams *PageGoForwardParams `json:"PageGoForwardParams,omitempty"`

	// PageGotoParams corresponds to the JSON schema field "PageGotoParams".
	PageGotoParams *PageGotoParams `json:"PageGotoParams,omitempty"`

	// PageHoverOptions corresponds to the JSON schema field "PageHoverOptions".
	PageHoverOptions *PageHoverOptions `json:"PageHoverOptions,omitempty"`

	// PageHoverParams corresponds to the JSON schema field "PageHoverParams".
	PageHoverParams *PageHoverParams `json:"PageHoverParams,omitempty"`

	// PageIDParams corresponds to the JSON schema field "PageIdParams".
	PageIDParams *PageIDParams `json:"PageIdParams,omitempty"`

	// PageKeyPressOptions corresponds to the JSON schema field "PageKeyPressOptions".
	PageKeyPressOptions *PageKeyPressOptions `json:"PageKeyPressOptions,omitempty"`

	// PageKeyPressParams corresponds to the JSON schema field "PageKeyPressParams".
	PageKeyPressParams *PageKeyPressParams `json:"PageKeyPressParams,omitempty"`

	// PageNavigationOptions corresponds to the JSON schema field
	// "PageNavigationOptions".
	PageNavigationOptions *PageNavigationOptions `json:"PageNavigationOptions,omitempty"`

	// PageRef corresponds to the JSON schema field "PageRef".
	PageRef *PageRef `json:"PageRef,omitempty"`

	// PageReloadOptions corresponds to the JSON schema field "PageReloadOptions".
	PageReloadOptions *PageReloadOptions `json:"PageReloadOptions,omitempty"`

	// PageReloadParams corresponds to the JSON schema field "PageReloadParams".
	PageReloadParams *PageReloadParams `json:"PageReloadParams,omitempty"`

	// PageScreenshotClip corresponds to the JSON schema field "PageScreenshotClip".
	PageScreenshotClip *PageScreenshotClip `json:"PageScreenshotClip,omitempty"`

	// PageScreenshotOptions corresponds to the JSON schema field
	// "PageScreenshotOptions".
	PageScreenshotOptions *PageScreenshotOptions `json:"PageScreenshotOptions,omitempty"`

	// PageScreenshotParams corresponds to the JSON schema field
	// "PageScreenshotParams".
	PageScreenshotParams *PageScreenshotParams `json:"PageScreenshotParams,omitempty"`

	// PageScreenshotResult corresponds to the JSON schema field
	// "PageScreenshotResult".
	PageScreenshotResult *PageScreenshotResult `json:"PageScreenshotResult,omitempty"`

	// PageScrollOptions corresponds to the JSON schema field "PageScrollOptions".
	PageScrollOptions *PageScrollOptions `json:"PageScrollOptions,omitempty"`

	// PageScrollParams corresponds to the JSON schema field "PageScrollParams".
	PageScrollParams *PageScrollParams `json:"PageScrollParams,omitempty"`

	// PageSetExtraHTTPHeadersParams corresponds to the JSON schema field
	// "PageSetExtraHTTPHeadersParams".
	PageSetExtraHTTPHeadersParams *PageSetExtraHTTPHeadersParams `json:"PageSetExtraHTTPHeadersParams,omitempty"`

	// PageSetViewportSizeOptions corresponds to the JSON schema field
	// "PageSetViewportSizeOptions".
	PageSetViewportSizeOptions *PageSetViewportSizeOptions `json:"PageSetViewportSizeOptions,omitempty"`

	// PageSetViewportSizeParams corresponds to the JSON schema field
	// "PageSetViewportSizeParams".
	PageSetViewportSizeParams *PageSetViewportSizeParams `json:"PageSetViewportSizeParams,omitempty"`

	// PageSnapshotOptions corresponds to the JSON schema field "PageSnapshotOptions".
	PageSnapshotOptions *PageSnapshotOptions `json:"PageSnapshotOptions,omitempty"`

	// PageSnapshotParams corresponds to the JSON schema field "PageSnapshotParams".
	PageSnapshotParams *PageSnapshotParams `json:"PageSnapshotParams,omitempty"`

	// PageTitleResult corresponds to the JSON schema field "PageTitleResult".
	PageTitleResult *PageTitleResult `json:"PageTitleResult,omitempty"`

	// PageTypeOptions corresponds to the JSON schema field "PageTypeOptions".
	PageTypeOptions *PageTypeOptions `json:"PageTypeOptions,omitempty"`

	// PageTypeParams corresponds to the JSON schema field "PageTypeParams".
	PageTypeParams *PageTypeParams `json:"PageTypeParams,omitempty"`

	// PageURLResult corresponds to the JSON schema field "PageUrlResult".
	PageURLResult *PageURLResult `json:"PageUrlResult,omitempty"`

	// PageVoidResult corresponds to the JSON schema field "PageVoidResult".
	PageVoidResult *PageVoidResult `json:"PageVoidResult,omitempty"`

	// PageWaitForLoadStateParams corresponds to the JSON schema field
	// "PageWaitForLoadStateParams".
	PageWaitForLoadStateParams *PageWaitForLoadStateParams `json:"PageWaitForLoadStateParams,omitempty"`

	// PageWaitForSelectorOptions corresponds to the JSON schema field
	// "PageWaitForSelectorOptions".
	PageWaitForSelectorOptions *PageWaitForSelectorOptions `json:"PageWaitForSelectorOptions,omitempty"`

	// PageWaitForSelectorParams corresponds to the JSON schema field
	// "PageWaitForSelectorParams".
	PageWaitForSelectorParams *PageWaitForSelectorParams `json:"PageWaitForSelectorParams,omitempty"`

	// PageWaitForSelectorResult corresponds to the JSON schema field
	// "PageWaitForSelectorResult".
	PageWaitForSelectorResult *PageWaitForSelectorResult `json:"PageWaitForSelectorResult,omitempty"`

	// PageWaitForTimeoutParams corresponds to the JSON schema field
	// "PageWaitForTimeoutParams".
	PageWaitForTimeoutParams *PageWaitForTimeoutParams `json:"PageWaitForTimeoutParams,omitempty"`

	// ProxyConfig corresponds to the JSON schema field "ProxyConfig".
	ProxyConfig *ProxyConfig `json:"ProxyConfig,omitempty"`

	// RgbaColor corresponds to the JSON schema field "RgbaColor".
	RgbaColor *RgbaColor `json:"RgbaColor,omitempty"`

	// RuntimeConfigureParams corresponds to the JSON schema field
	// "RuntimeConfigureParams".
	RuntimeConfigureParams *RuntimeConfigureParams `json:"RuntimeConfigureParams,omitempty"`

	// RuntimeConfigureResult corresponds to the JSON schema field
	// "RuntimeConfigureResult".
	RuntimeConfigureResult *RuntimeConfigureResult `json:"RuntimeConfigureResult,omitempty"`

	// RuntimeLoopbackStatusResult corresponds to the JSON schema field
	// "RuntimeLoopbackStatusResult".
	RuntimeLoopbackStatusResult *RuntimeLoopbackStatusResult `json:"RuntimeLoopbackStatusResult,omitempty"`

	// SnapshotResult corresponds to the JSON schema field "SnapshotResult".
	SnapshotResult *SnapshotResult `json:"SnapshotResult,omitempty"`

	// StagehandActParams corresponds to the JSON schema field "StagehandActParams".
	StagehandActParams *StagehandActParams `json:"StagehandActParams,omitempty"`

	// StagehandCloseResult corresponds to the JSON schema field
	// "StagehandCloseResult".
	StagehandCloseResult *StagehandCloseResult `json:"StagehandCloseResult,omitempty"`

	// StagehandExtractParams corresponds to the JSON schema field
	// "StagehandExtractParams".
	StagehandExtractParams *StagehandExtractParams `json:"StagehandExtractParams,omitempty"`

	// StagehandInitParams corresponds to the JSON schema field "StagehandInitParams".
	StagehandInitParams *StagehandInitParams `json:"StagehandInitParams,omitempty"`

	// StagehandInitResult corresponds to the JSON schema field "StagehandInitResult".
	StagehandInitResult *StagehandInitResult `json:"StagehandInitResult,omitempty"`

	// StagehandLog corresponds to the JSON schema field "StagehandLog".
	StagehandLog *StagehandLog `json:"StagehandLog,omitempty"`

	// StagehandLogData corresponds to the JSON schema field "StagehandLogData".
	StagehandLogData StagehandLogData `json:"StagehandLogData,omitempty"`

	// StagehandLogLevel corresponds to the JSON schema field "StagehandLogLevel".
	StagehandLogLevel *StagehandLogLevel `json:"StagehandLogLevel,omitempty"`

	// StagehandMetrics corresponds to the JSON schema field "StagehandMetrics".
	StagehandMetrics *StagehandMetrics `json:"StagehandMetrics,omitempty"`

	// StagehandObserveParams corresponds to the JSON schema field
	// "StagehandObserveParams".
	StagehandObserveParams *StagehandObserveParams `json:"StagehandObserveParams,omitempty"`

	// StagehandPingResult corresponds to the JSON schema field "StagehandPingResult".
	StagehandPingResult *StagehandPingResult `json:"StagehandPingResult,omitempty"`

	// TelemetryConfig corresponds to the JSON schema field "TelemetryConfig".
	TelemetryConfig *TelemetryConfig `json:"TelemetryConfig,omitempty"`

	// TelemetryTraces corresponds to the JSON schema field "TelemetryTraces".
	TelemetryTraces *TelemetryTraces `json:"TelemetryTraces,omitempty"`

	// VariablePrimitive corresponds to the JSON schema field "VariablePrimitive".
	VariablePrimitive *VariablePrimitive `json:"VariablePrimitive,omitempty"`

	// VariableValue corresponds to the JSON schema field "VariableValue".
	VariableValue *VariableValue `json:"VariableValue,omitempty"`

	// Variables corresponds to the JSON schema field "Variables".
	Variables Variables `json:"Variables,omitempty"`

	// Schema0 corresponds to the JSON schema field "__schema0".
	Schema0 json.RawMessage `json:"__schema0,omitempty"`

	// Schema1 corresponds to the JSON schema field "__schema1".
	Schema1 json.RawMessage `json:"__schema1,omitempty"`

	// Schema2 corresponds to the JSON schema field "__schema2".
	Schema2 json.RawMessage `json:"__schema2,omitempty"`

	// Schema3 corresponds to the JSON schema field "__schema3".
	Schema3 json.RawMessage `json:"__schema3,omitempty"`

	// Schema4 corresponds to the JSON schema field "__schema4".
	Schema4 json.RawMessage `json:"__schema4,omitempty"`

	// Schema5 corresponds to the JSON schema field "__schema5".
	Schema5 json.RawMessage `json:"__schema5,omitempty"`

	// Schema6 corresponds to the JSON schema field "__schema6".
	Schema6 json.RawMessage `json:"__schema6,omitempty"`

	// Schema7 corresponds to the JSON schema field "__schema7".
	Schema7 json.RawMessage `json:"__schema7,omitempty"`

	// Schema8 corresponds to the JSON schema field "__schema8".
	Schema8 json.RawMessage `json:"__schema8,omitempty"`
}
