import { mkdir, readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { z } from "zod/v4";
import {
  JSONRPCErrorResponseSchema,
  JSONRPCNotificationSchema,
  JSONRPCRequestSchema,
  JSONRPCSuccessResponseSchema,
} from "./schemas.ts";
import { toWireJsonSchema } from "./wire-casing.ts";

const PROTOCOL_DOCUMENT_ID = "stagehand.v4" as const;
const cdpEventsOutputUrl = new URL("../generated/cdp-events.ts", import.meta.url);

type CDPProtocolDocument = {
  domains: Array<{
    domain: string;
    events?: Array<{ name: string }>;
  }>;
};

export function collectCDPEventNames(documents: readonly CDPProtocolDocument[]): string[] {
  const names = documents.flatMap((document) =>
    document.domains.flatMap((domain) =>
      (domain.events ?? []).map((event) => `${domain.domain}.${event.name}`),
    ),
  );
  return [...new Set(names)].sort();
}

export async function loadOfficialCDPEventNames(): Promise<string[]> {
  const packageJsonUrl = new URL(import.meta.resolve("devtools-protocol/package.json"));
  const protocolUrls = [
    new URL("./json/browser_protocol.json", packageJsonUrl),
    new URL("./json/js_protocol.json", packageJsonUrl),
  ];
  const documents = await Promise.all(
    protocolUrls.map(async (url) => JSON.parse(await readFile(url, "utf8")) as CDPProtocolDocument),
  );
  return collectCDPEventNames(documents);
}

export function renderCDPEventNames(names: readonly string[]): string {
  const values = names.map((name) => `  ${JSON.stringify(name)},`).join("\n");
  return `// Generated by packages/protocol/json-rpc/build-json-rpc-schema.ts. Do not edit.\nimport { z } from "zod/v4";\n\nexport const CDP_EVENT_NAMES = [\n${values}\n] as const;\n\nexport const CDPEventNameSchema = z.enum(CDP_EVENT_NAMES).meta({ id: "CDPEventName" });\n`;
}

async function writeCDPEventNames(): Promise<void> {
  await mkdir(new URL("../generated/", import.meta.url), { recursive: true });
  await writeFile(
    cdpEventsOutputUrl,
    renderCDPEventNames(await loadOfficialCDPEventNames()),
    "utf8",
  );
}

async function buildStagehandProtocolDocument(): Promise<Record<string, unknown>> {
  // CDP event names must exist before these modules load because schemas.ts imports
  // the generated file. Keeping these imports dynamic makes a clean build self-bootstrapping.
  const [{ StagehandMethods, StagehandNotifications }, { BrowserbaseSessionCreateParamsSchema }] =
    await Promise.all([import("../schema-registry.ts"), import("../schemas.ts")]);
  const methodEntries = Object.values(StagehandMethods);
  const notificationEntries = Object.values(StagehandNotifications);

  const notificationEnvelopeSchemas = notificationEntries.map((notification) =>
    JSONRPCNotificationSchema.extend({
      method: z.literal(notification.name),
      params: notification.params,
    }),
  );
  const requestEnvelopeSchemas = methodEntries.map((method) =>
    JSONRPCRequestSchema.extend({
      method: z.literal(method.name),
      params: method.params,
    }),
  );

  const StagehandProtocolDocumentSchema = z
    .strictObject({
      methods: z.strictObject(
        Object.fromEntries(
          methodEntries.map((method) => [
            method.name,
            z.strictObject({ params: method.params, result: method.result }),
          ]),
        ),
      ),
      notifications: z.strictObject(
        Object.fromEntries(
          notificationEntries.map((notification) => [
            notification.name,
            z.strictObject({ params: notification.params }),
          ]),
        ),
      ),
      legacyClientModels: z
        .strictObject({
          browserbaseSessionCreateParams: BrowserbaseSessionCreateParamsSchema,
        })
        .optional(),
      jsonrpc: z.strictObject({
        request: z
          .union([requestEnvelopeSchemas[0]!, ...requestEnvelopeSchemas.slice(1)])
          .meta({ id: "StagehandRpcRequest" }),
        notification: (notificationEnvelopeSchemas.length === 1
          ? notificationEnvelopeSchemas[0]!
          : z.union([notificationEnvelopeSchemas[0]!, ...notificationEnvelopeSchemas.slice(1)])
        ).meta({ id: "StagehandRpcNotification" }),
        successResponse: JSONRPCSuccessResponseSchema,
        errorResponse: JSONRPCErrorResponseSchema,
      }),
    })
    .meta({ id: "StagehandProtocolDocument", title: "Stagehand V4 Protocol" });

  const preservedDocumentPropertyNames = new Set([
    "methods",
    "notifications",
    "jsonrpc",
    "request",
    "notification",
    "successResponse",
    "errorResponse",
    "params",
    "result",
    ...methodEntries.map((method) => method.name),
    ...notificationEntries.map((notification) => notification.name),
  ]);
  const generated = toWireJsonSchema(
    z.toJSONSchema(StagehandProtocolDocumentSchema, {
      io: "input",
      unrepresentable: "any",
    }),
    preservedDocumentPropertyNames,
  ) as Record<string, unknown>;
  const { $schema, ...document } = generated;
  return {
    $schema,
    $id: `https://stagehand.dev/schema/${PROTOCOL_DOCUMENT_ID}.json`,
    ...document,
  };
}

export async function buildProtocolArtifacts(): Promise<void> {
  await writeCDPEventNames();
  await writeFile(
    new URL(`../${PROTOCOL_DOCUMENT_ID}.json`, import.meta.url),
    `${JSON.stringify(await buildStagehandProtocolDocument(), null, 2)}\n`,
    "utf8",
  );
}

const entrypoint = process.argv[1];
if (entrypoint && import.meta.url === pathToFileURL(entrypoint).href) {
  await buildProtocolArtifacts();
}
