import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { pathToFileURL } from "node:url";

const execFileAsync = promisify(execFile);
const versionPattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/u;

type PublishedPackage = {
  name?: unknown;
  version?: unknown;
};

export function browseVersionFromCliPackageJson(value: string): string | undefined {
  const pkg = JSON.parse(value) as PublishedPackage;
  if (pkg.name !== "browse") throw new Error(`Expected browse package, found: ${String(pkg.name)}`);
  if (typeof pkg.version !== "string") {
    throw new Error(`Invalid published Browse version: ${String(pkg.version)}`);
  }
  if (!versionPattern.test(pkg.version)) return undefined;
  return pkg.version;
}

export function sha256Hex(value: Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

export function renderBrowseFormula(version: string, sha256: string): string {
  if (!versionPattern.test(version)) throw new Error(`Invalid Browse version: ${version}`);
  if (!/^[a-f0-9]{64}$/u.test(sha256)) throw new Error(`Invalid SHA-256: ${sha256}`);

  return `# typed: false
# frozen_string_literal: true

# This file is generated by the Stagehand release workflow. Do not edit it manually.
class Browse < Formula
  desc "CLI for browser automation and Browserbase cloud APIs"
  homepage "https://github.com/browserbase/stagehand/tree/main/packages/cli"
  url "https://registry.npmjs.org/browse/-/browse-${version}.tgz"
  sha256 "${sha256}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args

    platform = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x64"
    libexec.glob("lib/node_modules/browse/node_modules/*/prebuilds/*").each do |prebuild|
      rm_r prebuild if prebuild.basename.to_s != "#{platform}-#{arch}"
    end

    (bin/"browse").write_env_script libexec/"bin/browse", BROWSE_INSTALL_METHOD: "homebrew"
  end

  def caveats
    <<~EOS
      Local browser sessions require Chrome or Chromium.

      macOS users can install Google Chrome with:
        brew install --cask google-chrome

      Linux users should install Chrome or Chromium with their system package manager.
      You can also set CHROME_PATH, attach with --cdp, or use --remote with
      BROWSERBASE_API_KEY instead of installing a local browser.
    EOS
  end

  test do
    ENV["BROWSE_LOAD_DOTENV"] = "0"
    assert_match version.to_s, shell_output("#{bin}/browse --version")
  end
end
`;
}

export async function writeFormulaIfChanged(file: string, formula: string): Promise<boolean> {
  const current = await readFile(file, "utf8").catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return undefined;
    throw error;
  });
  if (current === formula) return false;

  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, formula);
  return true;
}

async function git(
  cwd: string,
  args: string[],
  env: NodeJS.ProcessEnv = process.env,
): Promise<void> {
  await execFileAsync("git", args, { cwd, env });
}

async function publishHomebrew(version: string): Promise<void> {
  if (!versionPattern.test(version)) throw new Error(`Invalid Browse version: ${version}`);
  const token = process.env.GITHUB_TOKEN;
  if (token === undefined || token === "") {
    throw new Error("GITHUB_TOKEN is required to update the Homebrew tap");
  }

  const tarballUrl = `https://registry.npmjs.org/browse/-/browse-${version}.tgz`;
  const response = await fetch(tarballUrl);
  if (!response.ok) {
    throw new Error(`npm returned ${response.status} while downloading browse ${version}`);
  }
  const sha256 = sha256Hex(new Uint8Array(await response.arrayBuffer()));
  const formula = renderBrowseFormula(version, sha256);
  const temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), "stagehand-homebrew-"));
  const tapDirectory = path.join(temporaryDirectory, "homebrew-tap");
  const askpass = path.join(temporaryDirectory, "git-askpass.sh");

  try {
    await writeFile(
      askpass,
      `#!/bin/sh
case "$1" in
  *Username*) printf '%s\\n' 'x-access-token' ;;
  *) printf '%s\\n' "$GITHUB_TOKEN" ;;
esac
`,
    );
    await chmod(askpass, 0o700);
    const gitEnvironment = {
      ...process.env,
      GIT_ASKPASS: askpass,
      GIT_TERMINAL_PROMPT: "0",
      GITHUB_TOKEN: token,
    };
    await git(
      temporaryDirectory,
      ["clone", "https://github.com/browserbase/homebrew-tap.git", tapDirectory],
      gitEnvironment,
    );
    const changed = await writeFormulaIfChanged(
      path.join(tapDirectory, "Formula/browse.rb"),
      formula,
    );
    if (!changed) {
      process.stdout.write(`Homebrew formula already matches browse ${version}\n`);
      return;
    }

    await git(tapDirectory, [
      "config",
      "user.name",
      `${process.env.GITHUB_APP_SLUG ?? "browserbase"}[bot]`,
    ]);
    await git(tapDirectory, [
      "config",
      "user.email",
      `${process.env.GITHUB_APP_SLUG ?? "browserbase"}[bot]@users.noreply.github.com`,
    ]);
    await git(tapDirectory, ["add", "Formula/browse.rb"]);
    await git(tapDirectory, ["commit", "-m", `Update browse to v${version}`]);
    await git(tapDirectory, ["push", "origin", "HEAD:main"], gitEnvironment);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

const invokedPath = process.argv[1];
if (
  invokedPath !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(invokedPath)).href
) {
  if (process.argv[2] === "--status") {
    const packageJson = await readFile(path.join(process.cwd(), "packages/cli/package.json"), "utf8");
    process.stdout.write(`version=${browseVersionFromCliPackageJson(packageJson) ?? ""}\n`);
  } else {
    const version = process.argv[2];
    if (version === undefined) throw new Error("Usage: publish-homebrew.ts <version>");
    await publishHomebrew(version);
  }
}
