import { mkdir, readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

type CDPProtocolDocument = {
  domains: Array<{
    domain: string;
    events?: Array<{ name: string }>;
  }>;
};

const outputUrl = new URL("../generated/cdp-events.ts", import.meta.url);

export function collectCDPEventNames(documents: readonly CDPProtocolDocument[]): string[] {
  const names = documents.flatMap((document) =>
    document.domains.flatMap((domain) =>
      (domain.events ?? []).map((event) => `${domain.domain}.${event.name}`),
    ),
  );
  return [...new Set(names)].sort();
}

export async function loadOfficialCDPEventNames(): Promise<string[]> {
  const packageJsonUrl = new URL(import.meta.resolve("devtools-protocol/package.json"));
  const protocolUrls = [
    new URL("./json/browser_protocol.json", packageJsonUrl),
    new URL("./json/js_protocol.json", packageJsonUrl),
  ];
  const documents = await Promise.all(
    protocolUrls.map(async (url) => JSON.parse(await readFile(url, "utf8")) as CDPProtocolDocument),
  );
  return collectCDPEventNames(documents);
}

export function renderCDPEventNames(names: readonly string[]): string {
  const values = names.map((name) => `  ${JSON.stringify(name)},`).join("\n");
  return `// Generated by packages/protocol/scripts/generate-cdp-event-names.ts. Do not edit.\nimport { z } from "zod/v4";\n\nexport const CDP_EVENT_NAMES = [\n${values}\n] as const;\n\nexport const CDPEventNameSchema = z.enum(CDP_EVENT_NAMES).meta({ id: "CDPEventName" });\n`;
}

async function main(): Promise<void> {
  const expected = renderCDPEventNames(await loadOfficialCDPEventNames());
  if (process.argv.includes("--check")) {
    const current = await readFile(outputUrl, "utf8").catch(() => "");
    if (current !== expected) {
      throw new Error("Generated CDP event names are stale; run the protocol build");
    }
    return;
  }
  await mkdir(new URL("../generated/", import.meta.url), { recursive: true });
  await writeFile(outputUrl, expected);
}

const entrypoint = process.argv[1];
if (entrypoint && import.meta.url === pathToFileURL(entrypoint).href) {
  await main();
}
