#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates Ruby wire models from packages/protocol/stagehand.v4.json.
#
# Stdlib-only on purpose: `just generate` must be able to run this without a
# `bundle install`. Mirrors packages/sdk-python/scripts/generate.py: the
# JSON-RPC envelope definitions are excluded (the envelope is hand-written in
# rpc_client.rb) and a --check mode fails when the generated files are stale.

require "json"

PACKAGES_ROOT = File.expand_path("../..", __dir__)
PROTOCOL_PATH = File.join(PACKAGES_ROOT, "protocol", "stagehand.v4.json")
PROTOCOL_PACKAGE_PATH = File.join(PACKAGES_ROOT, "protocol", "package.json")
SDK_ROOT = File.expand_path("..", __dir__)
MODELS_PATH = File.join(SDK_ROOT, "lib", "stagehand", "generated", "models.rb")
PROTOCOL_VERSION_PATH = File.join(SDK_ROOT, "lib", "stagehand", "generated", "protocol_version.rb")

SEMVER_PATTERN_TEXT =
  "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)" \
  "(?:-((?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*)" \
  "(?:\\.(?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*))*))?" \
  "(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$"

# The transport envelopes are hand-written client code, not public data models.
ENVELOPE_DEFS = %w[
  StagehandRpcRequest
  StagehandRpcNotification
  JSONRPCSuccessResponse
  JSONRPCErrorResponse
].freeze

CONSTANT_NAME = /\A[A-Z][A-Za-z0-9_]*\z/
FIELD_NAME = /\A[a-z_][a-z0-9_]*\z/

class Generator
  def initialize(protocol)
    @defs = protocol.fetch("$defs").reject { |name, _| ENVELOPE_DEFS.include?(name) }
    properties = protocol.fetch("properties")
    @methods = properties.fetch("methods").fetch("properties")
    @notifications = properties.fetch("notifications").fetch("properties")
    @kinds = classify
    @compiled = @defs.to_h { |name, schema| [name, compile(schema)] }
  end

  def models_module
    lines = []
    lines << "# frozen_string_literal: true"
    lines << ""
    lines << "# Generated by scripts/generate.rb from packages/protocol/stagehand.v4.json."
    lines << "# DO NOT EDIT."
    lines << ""
    lines << 'require_relative "../wire"'
    lines << ""
    lines << "module Stagehand"
    lines << "  module Models"
    @defs.each do |name, schema|
      case @kinds.fetch(name)
      when :class then lines.concat(class_source(name, schema))
      when :enum then lines.concat(enum_source(name, schema))
      end
    end
    lines.concat(defs_registry_source)
    lines.concat(registry_source("METHODS", @methods, %w[params result]))
    lines.concat(registry_source("NOTIFICATIONS", @notifications, %w[params]))
    lines << "  end"
    lines << "end"
    "#{lines.join("\n")}\n"
  end

  def protocol_version_module
    package = JSON.parse(File.read(PROTOCOL_PACKAGE_PATH))
    version = package.fetch("version")
    raise "expected protocol package version to be a string" unless version.is_a?(String)
    raise "invalid Stagehand protocol package version: #{version}" unless Regexp.new(SEMVER_PATTERN_TEXT).match?(version)

    <<~RUBY
      # frozen_string_literal: true

      # Generated from packages/protocol/package.json. DO NOT EDIT.

      module Stagehand
        STAGEHAND_PROTOCOL_VERSION = #{version.inspect}
        PROTOCOL_SEMVER_PATTERN = Regexp.new(#{SEMVER_PATTERN_TEXT.inspect})
      end
    RUBY
  end

  private

  def classify
    @defs.to_h do |name, schema|
      kind =
        if schema.is_a?(Hash) && schema["type"] == "object" && schema.key?("properties") &&
           schema["properties"].keys.all? { |field| FIELD_NAME.match?(field) }
          # Objects with non-attribute property names (e.g. LLMToolJson carries a
          # literal "$schema" key) stay raw wire hashes instead of classes.
          :class
        elsif schema.is_a?(Hash) && schema["type"] == "string" && schema.key?("enum")
          :enum
        else
          :descriptor
        end
      if kind != :descriptor && !CONSTANT_NAME.match?(name)
        raise "definition #{name} cannot become a Ruby constant"
      end
      [name, kind]
    end
  end

  # Compiles a schema node to a wire descriptor: nil (raw JSON), a definition
  # name, [:array, d], [:map, d], or [:union, [d, ...]].
  def compile(node)
    return nil unless node.is_a?(Hash)

    if (ref = node["$ref"])
      name = ref.delete_prefix("#/$defs/")
      raise "unsupported $ref: #{ref}" if name == ref
      return ENVELOPE_DEFS.include?(name) ? nil : name
    end

    if (variants = node["anyOf"] || node["oneOf"])
      compiled = variants.map { |variant| compile(variant) }
      structured = compiled.compact
      return nil if structured.empty?
      # A trailing nil marks an "open" union: at least one variant was a
      # scalar/null/opaque schema, so any unmatched value stays raw. Closed
      # unions (every variant structured) decode strictly.
      return [:union, structured.length == compiled.length ? structured : structured + [nil]]
    end

    case node["type"]
    when "object"
      # Inline objects with properties stay raw: every named object lives in $defs.
      return nil if node.key?("properties")
      additional = node["additionalProperties"]
      return nil unless additional.is_a?(Hash)
      inner = compile(additional)
      inner.nil? ? nil : [:map, inner]
    when "array"
      items = node["items"]
      return nil unless items.is_a?(Hash)
      inner = compile(items)
      inner.nil? ? nil : [:array, inner]
    else
      nil
    end
  end

  # A descriptor is trivial when it can never reach a generated class, so
  # decoding it is the identity. Cycles (recursive JSON values) are trivial.
  def trivial?(descriptor, seen = {})
    case descriptor
    when nil then true
    when String
      return true if seen[descriptor]
      seen[descriptor] = true
      return false if @kinds[descriptor] == :class
      return true if @kinds[descriptor] == :enum
      trivial?(@compiled.fetch(descriptor), seen)
    when Array
      kind, inner = descriptor
      kind == :union ? inner.all? { |variant| trivial?(variant, seen) } : trivial?(inner, seen)
    end
  end

  def simplify(descriptor)
    trivial?(descriptor) ? nil : descriptor
  end

  def literal(descriptor)
    case descriptor
    when nil then "nil"
    when String then descriptor.inspect
    when Array
      kind, inner = descriptor
      if kind == :union
        "[:union, [#{inner.map { |variant| literal(variant) }.join(", ")}].freeze].freeze"
      else
        "[:#{kind}, #{literal(inner)}].freeze"
      end
    end
  end

  def class_source(name, schema)
    properties = schema.fetch("properties")
    required = schema.fetch("required", [])
    properties.each_key do |field|
      raise "property #{name}.#{field} is not a valid Ruby attribute name" unless FIELD_NAME.match?(field)
    end

    lines = []
    lines << ""
    lines << "    class #{name} < Stagehand::Wire::Model"
    if properties.empty?
      lines << "      FIELDS = {}.freeze"
    else
      lines << "      FIELDS = {"
      properties.each do |field, node|
        lines << "        #{field.inspect} => #{literal(simplify(compile(node)))},"
      end
      lines << "      }.freeze"
    end
    lines << "      REQUIRED = #{required.empty? ? "[].freeze" : "%w[#{required.join(" ")}].freeze"}"
    unless properties.empty?
      lines << "      attr_reader #{properties.keys.map { |field| ":#{field}" }.join(", ")}"
    end
    lines << "    end"
    lines
  end

  def enum_source(name, schema)
    values = schema.fetch("enum")
    [
      "",
      "    module #{name}",
      "      VALUES = %w[#{values.join(" ")}].freeze",
      "    end",
    ]
  end

  def defs_registry_source
    lines = ["", "    DEFS = {"]
    @defs.each_key do |name|
      value =
        case @kinds.fetch(name)
        when :class then name
        when :enum then "nil"
        else literal(simplify(@compiled.fetch(name)))
        end
      lines << "      #{name.inspect} => #{value},"
    end
    lines << "    }.freeze"
    lines
  end

  def registry_source(constant, entries, roles)
    lines = ["", "    #{constant} = {"]
    entries.each do |method, schema|
      properties = schema.fetch("properties")
      pairs = roles.map do |role|
        raise "#{constant} entry #{method} is missing #{role}" unless properties.key?(role)
        "#{role}: #{literal(simplify(compile(properties.fetch(role))))}"
      end
      lines << "      #{method.inspect} => { #{pairs.join(", ")} }.freeze,"
    end
    lines << "    }.freeze"
    lines
  end
end

def main
  check = ARGV.include?("--check")

  protocol = JSON.parse(File.read(PROTOCOL_PATH))
  generator = Generator.new(protocol)
  outputs = {
    MODELS_PATH => generator.models_module,
    PROTOCOL_VERSION_PATH => generator.protocol_version_module,
  }

  if check
    stale = outputs.reject { |path, expected| File.file?(path) && File.read(path) == expected }.keys
    unless stale.empty?
      relative = stale.map { |path| path.delete_prefix("#{SDK_ROOT}/") }
      abort "generated Ruby files are stale: #{relative.join(", ")}"
    end
    return
  end

  outputs.each do |path, content|
    Dir.mkdir(File.dirname(path)) unless Dir.exist?(File.dirname(path))
    File.write(path, content)
  end
end

main
