import { OUTCOME_LABELS } from "../scorecard.js";
import type { Scorecard } from "../types.js";

const pct = (n: number) => `${Math.round(n * 100)}%`;

function featureLine(s: Scorecard): string {
  const f = s.features;
  const on = (b: boolean) => (b ? "✅" : "❌");
  return [
    `Advanced Stealth ${on(f.advancedStealth)}`,
    `Residential Proxies ${on(f.proxies)}${f.proxyCountry ? ` (${f.proxyCountry})` : ""}`,
    `CAPTCHA Solving ${on(f.solveCaptchas)}`,
    `Ad Blocking ${on(f.blockAds)}`,
  ].join(" · ");
}

/** The "acceptance matrix" CEs build by hand — one row per site, machine-made. */
export function renderMarkdown(s: Scorecard): string {
  const lines: string[] = [];
  lines.push(`# ${s.name} — Results Scorecard`);
  if (s.customer) lines.push(`**Customer:** ${s.customer}  `);
  lines.push(`**Run:** ${s.startedAt} → ${s.finishedAt}  `);
  lines.push(`**Region:** ${s.region} · **Model:** ${s.model}  `);
  lines.push(`**Config:** ${featureLine(s)}`);
  lines.push("");

  // Headline.
  const headline =
    `> **${s.sitesMet}/${s.siteCount} sites hit their target.** ` +
    `Overall ${pct(s.overallRate)} success across ${s.totalAttempts} attempts.`;
  lines.push(headline);
  lines.push("");

  // Acceptance matrix.
  lines.push("## Acceptance Matrix");
  lines.push("");
  lines.push("| Site | Task | Success | Target | Result | Top failure | Anti-bot seen |");
  lines.push("|------|------|---------|--------|--------|-------------|---------------|");
  for (const site of s.sites) {
    const result = site.met ? "✅ Met" : "❌ Below";
    const fail = site.topFailure ? OUTCOME_LABELS[site.topFailure] : "—";
    const seen = site.detected.length ? site.detected.join(", ") : (site.antibot ?? "—");
    lines.push(
      `| ${site.name} | ${escapeCell(site.task)} | ${site.passes}/${site.attempts} (${pct(site.successRate)}) | ${pct(site.target)} | ${result} | ${fail} | ${seen} |`,
    );
  }
  lines.push("");

  // Per-site detail with session replay links (the evidence customers want).
  lines.push("## Session Detail");
  for (const site of s.sites) {
    lines.push("");
    lines.push(`### ${site.name} — ${pct(site.successRate)} (${site.passes}/${site.attempts})`);
    lines.push("");
    lines.push("| # | Outcome | Reason | Replay |");
    lines.push("|---|---------|--------|--------|");
    for (const r of site.results) {
      const icon = r.success ? "🟢" : "🔴";
      const replay = r.replayUrl ? `[session](${r.replayUrl})` : "—";
      lines.push(
        `| ${r.attempt} | ${icon} ${OUTCOME_LABELS[r.outcome]} | ${escapeCell(r.reason)} | ${replay} |`,
      );
    }
  }
  lines.push("");
  lines.push("---");
  lines.push(
    `_Generated by [bbpoc](https://github.com/browserbase/bbpoc) · Browserbase verified-trial harness._`,
  );
  return lines.join("\n");
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 160);
}
