name: Publish CTRF report
description: Convert JUnit to CTRF (optional) and publish CTRF report with Insights.
inputs:
  junit-path:
    description: Path to the JUnit XML report.
    required: false
    default: ""
  tool:
    description: Tool name for the CTRF report (e.g. playwright, vitest, node-test).
    required: false
    default: "junit"
  github-token:
    description: GitHub token for publishing CTRF reports.
    required: true

outputs:
  artifact-name:
    description: Name of the CTRF artifact uploaded by the reporter.
    value: ${{ steps.ctrf-meta.outputs.ARTIFACT_NAME }}
  report-path:
    description: CTRF report path or glob.
    value: ${{ steps.ctrf-meta.outputs.REPORT_PATH }}

runs:
  using: composite
  steps:
    - name: Set CTRF metadata
      id: ctrf-meta
      shell: bash
      run: |
        junit_path="${{ inputs.junit-path }}"
        if [ -n "$junit_path" ]; then
          rel_path="${junit_path##*/ctrf/}"
          rel_path="${rel_path%.xml}"
          safe_name="${rel_path//\//-}"
          echo "ARTIFACT_NAME=ctrf-${safe_name}" >> "$GITHUB_OUTPUT"
          echo "REPORT_PATH=ctrf/${safe_name}.json" >> "$GITHUB_OUTPUT"
        else
          job_name="${GITHUB_JOB:-ctrf-report}"
          echo "ARTIFACT_NAME=ctrf-${job_name}" >> "$GITHUB_OUTPUT"
          echo "REPORT_PATH=./ctrf/*.json" >> "$GITHUB_OUTPUT"
        fi

    - name: Convert JUnit to CTRF
      if: ${{ inputs.junit-path != '' }}
      shell: bash
      run: |
        junit_path="${{ inputs.junit-path }}"
        if [ -f "$junit_path" ]; then
          pnpm dlx junit-to-ctrf "$junit_path" \
            -o "${{ steps.ctrf-meta.outputs.REPORT_PATH }}" \
            -t "${{ inputs.tool }}"
        else
          echo "JUnit report not found at $junit_path"
        fi

    - name: Publish Test Report with Insights
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: './ctrf/*.json'
        summary: false
        summary-report: true
        summary-delta-report: false
        test-report: true
        failed-report: true
        insights-report: true
        flaky-rate-report: true
        fail-rate-report: true
        slowest-report: true
        previous-results-report: false
        fetch-previous-results: false
        upload-artifact: true
        artifact-name: ${{ steps.ctrf-meta.outputs.ARTIFACT_NAME }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
