name: Publish CTRF report
description: Convert JUnit to CTRF (optional) and publish CTRF report with Insights.
inputs:
  junit-path:
    description: Path to the JUnit XML report.
    required: false
    default: ""
  tool:
    description: Tool name for the CTRF report (e.g. playwright, vitest, node-test).
    required: false
    default: "junit"
  github-token:
    description: GitHub token for publishing CTRF reports.
    required: true

outputs:
  artifact-name:
    description: Name of the CTRF artifact uploaded by the reporter.
    value: ${{ steps.ctrf-meta.outputs.ARTIFACT_NAME }}
  report-path:
    description: CTRF report path or glob.
    value: ${{ steps.ctrf-meta.outputs.REPORT_PATH }}

runs:
  using: composite
  steps:
    - name: Set CTRF metadata
      id: ctrf-meta
      shell: bash
      run: |
        junit_path="${{ inputs.junit-path }}"
        if [ -n "$junit_path" ]; then
          rel_path="${junit_path##*/ctrf/}"
          rel_path="${rel_path%.xml}"
          safe_name="${rel_path//\//-}"
          echo "ARTIFACT_NAME=ctrf-${safe_name}" >> "$GITHUB_OUTPUT"
          echo "REPORT_PATH=ctrf/${safe_name}.json" >> "$GITHUB_OUTPUT"
        else
          job_name="${GITHUB_JOB:-ctrf-report}"
          safe_job_name="${job_name//\//-}"
          echo "ARTIFACT_NAME=ctrf-${safe_job_name}" >> "$GITHUB_OUTPUT"
          echo "REPORT_PATH=./ctrf/*.json" >> "$GITHUB_OUTPUT"
        fi

    - name: Convert JUnit to CTRF
      if: ${{ inputs.junit-path != '' }}
      shell: bash
      run: |
        junit_path="${{ inputs.junit-path }}"
        if [ -f "$junit_path" ]; then
          if [ ! -s "$junit_path" ]; then
            echo "JUnit report is empty at $junit_path"
            exit 0
          fi
          if ! pnpm dlx junit-to-ctrf "$junit_path" \
            -o "${{ steps.ctrf-meta.outputs.REPORT_PATH }}" \
            -t "${{ inputs.tool }}"; then
            echo "JUnit-to-CTRF conversion failed; leaving no CTRF report."
            exit 0
          fi
        else
          echo "JUnit report not found at $junit_path"
          exit 0
        fi

    - name: Check CTRF report
      id: ctrf-report
      shell: bash
      run: |
        report_path="${{ steps.ctrf-meta.outputs.REPORT_PATH }}"
        if [ -f "$report_path" ]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Upload CTRF report artifact
      if: ${{ steps.ctrf-report.outputs.found == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.ctrf-meta.outputs.ARTIFACT_NAME }}
        path: ${{ steps.ctrf-meta.outputs.REPORT_PATH }}
