import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { zipSync } from "fflate";

const sdkDirectory = path.resolve(import.meta.dirname, "..");
const extensionDirectory = path.resolve(sdkDirectory, "../server/dist");
const outputDirectory = path.join(sdkDirectory, "src/generated");
const outputPath = path.join(outputDirectory, "stagehandExtensionArchive.generated.ts");
const ZIP_TIMESTAMP = new Date("1980-01-01T00:00:00.000Z");

const files = await readExtensionFiles(extensionDirectory);
if (!("manifest.json" in files)) {
  throw new Error(`Stagehand extension manifest was not found in ${extensionDirectory}`);
}

await mkdir(outputDirectory, { recursive: true });
const archive = zipSync(files, { level: 9, mtime: ZIP_TIMESTAMP });
const archiveDataUrl = `data:application/zip;base64,${Buffer.from(archive).toString("base64")}`;
await writeFile(
  outputPath,
  [
    "// Generated by scripts/build-extension-archive.ts. Do not edit.",
    "export const stagehandExtensionArchiveDataUrl =",
    `  ${JSON.stringify(archiveDataUrl)};`,
    "",
  ].join("\n"),
);

async function readExtensionFiles(
  directory: string,
  relativeDirectory = "",
): Promise<Record<string, Uint8Array>> {
  const absoluteDirectory = path.join(directory, relativeDirectory);
  const entries = await readdir(absoluteDirectory, { withFileTypes: true });
  const files: Record<string, Uint8Array> = {};

  for (const entry of entries.toSorted((left, right) => left.name.localeCompare(right.name))) {
    const relativePath = path.join(relativeDirectory, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`Stagehand extension archive cannot contain symbolic links: ${relativePath}`);
    }
    if (entry.isDirectory()) {
      Object.assign(files, await readExtensionFiles(directory, relativePath));
      continue;
    }
    if (!entry.isFile()) {
      throw new Error(`Stagehand extension archive contains an unsupported entry: ${relativePath}`);
    }
    files[relativePath.split(path.sep).join("/")] = await readFile(
      path.join(directory, relativePath),
    );
  }

  return files;
}
